import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma.service';
import { tenantStorage } from '../../common/tenant-context';
import { CreateManufacturingAssemblyConsumptionDto, CreateManufacturingAssemblyEvidenceDto, CreateManufacturingAssemblyExecutionDto, ManufacturingAssemblyOperationActionDto, StartManufacturingAssemblyTimeDto, StopManufacturingAssemblyTimeDto, UpdateManufacturingAssemblyOperationDto } from './dto/manufacturing-assembly.dto';

type Actor = { id: string; name: string; role: string };
const ACTIONS = new Set(['start', 'pause', 'resume', 'block', 'complete', 'not-applicable']);

@Injectable()
export class ManufacturingAssemblyService {
  constructor(private readonly prisma: PrismaService) {}
  private context() { const store = tenantStorage.getStore(); if (!store?.tenantId || !store?.userId) throw new ForbiddenException('Contexto de usuario incompleto'); return { tenantId: store.tenantId, userId: store.userId }; }
  private async actor(tx: any, tenantId: string, userId: string): Promise<Actor> { const actor = await tx.user.findFirst({ where: { id: userId, tenantId }, select: { id: true, name: true, role: true } }); if (!actor) throw new ForbiddenException('Usuario no encontrado'); return actor; }
  private async visibleOrder(tx: any, tenantId: string, orderId: string, actor: Actor) { const order = await tx.manufacturingOrder.findFirst({ where: { id: orderId, tenantId }, include: { members: { where: { userId: actor.id } } } }); if (!order || (actor.role === 'TECH' && order.responsibleUserId !== actor.id && !order.members.length)) throw new NotFoundException('Orden de manufactura no encontrada'); return order; }
  private text(value: unknown) { const normalized = String(value ?? '').trim(); return normalized || null; }
  private amount(value: unknown) { const amount = Number(value); if (!Number.isFinite(amount) || amount <= 0) throw new BadRequestException('La cantidad debe ser mayor que cero'); return amount; }
  private version(entity: any, raw: unknown) { const version = Number(raw); if (!Number.isInteger(version) || version !== entity.lockVersion) throw new ConflictException('La operación cambió; actualiza la pantalla'); }
  private include() { return { kit: { include: { manufacturedUnit: true, lines: { orderBy: { positionSnapshot: 'asc' } } } }, operations: { include: { timeLogs: { orderBy: { startedAt: 'desc' } }, evidence: { orderBy: { createdAt: 'desc' } }, consumptions: { include: { kitLine: true }, orderBy: { consumedAt: 'desc' } } }, orderBy: { position: 'asc' } } }; }

  async list(orderId: string) { const { tenantId, userId } = this.context(); const actor = await this.actor(this.prisma as any, tenantId, userId); await this.visibleOrder(this.prisma as any, tenantId, orderId, actor); const rows = await (this.prisma as any).manufacturingAssemblyExecution.findMany({ where: { tenantId, manufacturingOrderId: orderId }, include: this.include(), orderBy: { createdAt: 'asc' } }); return rows.map((row: any) => this.serialize(row)); }

  async create(kitId: string, dto: CreateManufacturingAssemblyExecutionDto) {
    const { tenantId, userId } = this.context(); let orderId = '';
    await this.prisma.$transaction(async (tx: any) => {
      const actor = await this.actor(tx, tenantId, userId); if (actor.role !== 'ADMIN') throw new ForbiddenException('Solo un administrador puede crear ejecuciones');
      await tx.$queryRaw`SELECT "id" FROM "ManufacturingKit" WHERE "id" = ${kitId} FOR UPDATE`;
      const kit = await tx.manufacturingKit.findFirst({ where: { id: kitId, tenantId }, include: { manufacturedUnit: true, manufacturingOrder: true } }); if (!kit) throw new NotFoundException('Kit no encontrado'); orderId = kit.manufacturingOrderId;
      if (kit.status !== 'RELEASED') throw new ConflictException('El kit debe estar liberado antes de crear el ensamble'); if (await tx.manufacturingAssemblyExecution.findUnique({ where: { kitId } })) throw new ConflictException('El kit ya tiene una ejecución de ensamble');
      const templateId = String(dto?.templateId || '').trim(); const template = await tx.assemblyTemplate.findFirst({ where: { id: templateId, tenantId, active: true }, include: { steps: { orderBy: { position: 'asc' } } } });
      if (!template || !template.steps.length) throw new ConflictException('Selecciona una plantilla activa con operaciones');
      const execution = await tx.manufacturingAssemblyExecution.create({ data: { tenantId, manufacturingOrderId: orderId, kitId, templateId: template.id, executionCode: `${kit.kitCode}-ENS`, templateCode: template.code, templateName: template.name, templateVersion: template.version, plannedMinutes: template.steps.reduce((sum: number, step: any) => sum + Number(step.estimatedMinutes), 0), createdByUserId: actor.id, createdByName: actor.name } });
      await tx.manufacturingAssemblyOperation.createMany({ data: template.steps.map((step: any) => ({ tenantId, executionId: execution.id, templateStepId: step.id, position: step.position, phase: step.phase, name: step.name, instructions: step.instructions, estimatedMinutes: step.estimatedMinutes, plannedTechnicians: step.plannedTechnicians, dependsOnPositions: step.dependsOnPositions, required: step.required, evidenceRequired: step.evidenceRequired })) });
      await this.audit(tx, tenantId, orderId, execution.id, 'MANUFACTURING_ASSEMBLY_CREATED', `${execution.executionCode}: ejecución creada`, actor, { kitId, templateId: template.id, operations: template.steps.length }); await tx.manufacturingOrder.update({ where: { id: orderId }, data: { version: { increment: 1 } } });
    }, { isolationLevel: 'Serializable' }); return this.list(orderId);
  }

  async updateOperation(operationId: string, dto: UpdateManufacturingAssemblyOperationDto) {
    const { tenantId, userId } = this.context(); let orderId = '';
    await this.prisma.$transaction(async (tx: any) => { const actor = await this.actor(tx, tenantId, userId); const operation = await this.lockedOperation(tx, tenantId, operationId, actor); orderId = operation.execution.manufacturingOrderId; this.version(operation, dto?.lockVersion); if (['COMPLETED', 'NOT_APPLICABLE'].includes(operation.status)) throw new ConflictException('La operación ya está cerrada'); const data: any = { lockVersion: { increment: 1 } }; if (dto.assignedUserId !== undefined) { if (actor.role !== 'ADMIN') throw new ForbiddenException('Solo un administrador puede asignar técnicos'); const id = this.text(dto.assignedUserId); if (id) { const user = await tx.user.findFirst({ where: { id, tenantId }, select: { id: true, name: true } }); if (!user) throw new BadRequestException('Técnico no válido'); data.assignedUserId = user.id; data.assignedUserName = user.name; } else { data.assignedUserId = null; data.assignedUserName = null; } } if (dto.notes !== undefined) data.notes = this.text(dto.notes); await tx.manufacturingAssemblyOperation.update({ where: { id: operation.id }, data }); await this.audit(tx, tenantId, orderId, operation.id, 'ASSEMBLY_OPERATION_UPDATED', `${operation.name}: datos actualizados`, actor, data); }); return this.list(orderId);
  }

  async operationAction(operationId: string, rawAction: string, dto: ManufacturingAssemblyOperationActionDto) {
    const action = String(rawAction || '').toLowerCase(); if (!ACTIONS.has(action)) throw new BadRequestException('Acción de operación inválida'); const { tenantId, userId } = this.context(); let orderId = '';
    await this.prisma.$transaction(async (tx: any) => {
      const actor = await this.actor(tx, tenantId, userId); const operation = await this.lockedOperation(tx, tenantId, operationId, actor); orderId = operation.execution.manufacturingOrderId; this.version(operation, dto?.lockVersion); if (['COMPLETED', 'NOT_APPLICABLE'].includes(operation.status)) throw new ConflictException('La operación ya está cerrada');
      let data: any = { lockVersion: { increment: 1 } }; let auditAction = ''; let summary = '';
      if (action === 'start') { if (!['PENDING', 'PAUSED', 'BLOCKED'].includes(operation.status)) throw new ConflictException('La operación no puede iniciarse en su estado actual'); await this.dependencies(tx, operation); data = { ...data, status: 'IN_PROGRESS', startedAt: operation.startedAt || new Date(), blockedReason: null }; auditAction = 'ASSEMBLY_OPERATION_STARTED'; summary = `${operation.name}: operación iniciada`; }
      if (action === 'pause') { if (operation.status !== 'IN_PROGRESS') throw new ConflictException('Solo una operación en proceso puede pausarse'); data.status = 'PAUSED'; auditAction = 'ASSEMBLY_OPERATION_PAUSED'; summary = `${operation.name}: operación pausada`; }
      if (action === 'resume') { if (!['PAUSED', 'BLOCKED'].includes(operation.status)) throw new ConflictException('La operación no está pausada o bloqueada'); await this.dependencies(tx, operation); data = { ...data, status: 'IN_PROGRESS', blockedReason: null }; auditAction = 'ASSEMBLY_OPERATION_RESUMED'; summary = `${operation.name}: operación reanudada`; }
      if (action === 'block') { const reason = this.text(dto?.reason); if (!reason || reason.length < 5) throw new BadRequestException('El bloqueo requiere un motivo de al menos 5 caracteres'); if (!['PENDING', 'IN_PROGRESS', 'PAUSED'].includes(operation.status)) throw new ConflictException('La operación no puede bloquearse'); data = { ...data, status: 'BLOCKED', blockedReason: reason }; auditAction = 'ASSEMBLY_OPERATION_BLOCKED'; summary = `${operation.name}: operación bloqueada`; }
      if (action === 'not-applicable') { if (operation.required) throw new ConflictException('Una operación obligatoria no puede marcarse como no aplicable'); if (actor.role !== 'ADMIN') throw new ForbiddenException('Solo un administrador puede omitir operaciones'); data = { ...data, status: 'NOT_APPLICABLE', progressPercent: 100, completedAt: new Date(), completedByUserId: actor.id, completedByName: actor.name }; auditAction = 'ASSEMBLY_OPERATION_NOT_APPLICABLE'; summary = `${operation.name}: no aplicable`; }
      if (action === 'complete') { await this.dependencies(tx, operation); if (!['IN_PROGRESS', 'PAUSED'].includes(operation.status)) throw new ConflictException('La operación debe estar iniciada para completarse'); const openLog = await tx.manufacturingAssemblyTimeLog.count({ where: { tenantId, operationId, endedAt: null } }); if (openLog) throw new ConflictException('Detén el registro de tiempo antes de completar'); if (operation.evidenceRequired) { const count = await tx.manufacturingAssemblyEvidence.count({ where: { tenantId, operationId } }); if (!count) throw new ConflictException('La operación requiere evidencia antes de completarse'); } data = { ...data, status: 'COMPLETED', progressPercent: 100, completedAt: new Date(), completedByUserId: actor.id, completedByName: actor.name, notes: this.text(dto?.notes) || operation.notes, blockedReason: null }; auditAction = 'ASSEMBLY_OPERATION_COMPLETED'; summary = `${operation.name}: operación completada`; }
      await tx.manufacturingAssemblyOperation.update({ where: { id: operation.id }, data }); if (action === 'start' && operation.execution.status === 'PLANNED') await tx.manufacturingAssemblyExecution.update({ where: { id: operation.executionId }, data: { status: 'IN_PROGRESS', startedAt: new Date(), lockVersion: { increment: 1 } } }); await this.completeExecutionIfReady(tx, tenantId, operation.executionId); await this.audit(tx, tenantId, orderId, operation.id, auditAction, summary, actor, { status: data.status, reason: dto?.reason }); await tx.manufacturingOrder.update({ where: { id: orderId }, data: { version: { increment: 1 } } });
    }, { isolationLevel: 'Serializable' }); return this.list(orderId);
  }

  async startTime(operationId: string, dto: StartManufacturingAssemblyTimeDto) { const { tenantId, userId } = this.context(); let orderId = ''; await this.prisma.$transaction(async (tx: any) => { const actor = await this.actor(tx, tenantId, userId); const operation = await this.lockedOperation(tx, tenantId, operationId, actor); orderId = operation.execution.manufacturingOrderId; if (operation.status !== 'IN_PROGRESS') throw new ConflictException('La operación debe estar en proceso'); if (await tx.manufacturingAssemblyTimeLog.count({ where: { tenantId, operationId, endedAt: null } })) throw new ConflictException('Ya existe un registro de tiempo activo'); const log = await tx.manufacturingAssemblyTimeLog.create({ data: { tenantId, operationId, userId: actor.id, userName: actor.name, startedAt: new Date(), note: this.text(dto?.note) } }); await this.audit(tx, tenantId, orderId, log.id, 'ASSEMBLY_TIME_STARTED', `${operation.name}: tiempo iniciado`, actor, { operationId }); }); return this.list(orderId); }
  async stopTime(logId: string, dto: StopManufacturingAssemblyTimeDto) { const { tenantId, userId } = this.context(); let orderId = ''; await this.prisma.$transaction(async (tx: any) => { const actor = await this.actor(tx, tenantId, userId); await tx.$queryRaw`SELECT "id" FROM "ManufacturingAssemblyTimeLog" WHERE "id" = ${logId} FOR UPDATE`; const log = await tx.manufacturingAssemblyTimeLog.findFirst({ where: { id: logId, tenantId }, include: { operation: { include: { execution: { include: { manufacturingOrder: { include: { members: true } } } } } } } }); if (!log) throw new NotFoundException('Registro de tiempo no encontrado'); orderId = log.operation.execution.manufacturingOrderId; if (log.endedAt) throw new ConflictException('El registro de tiempo ya está cerrado'); if (actor.role !== 'ADMIN' && log.userId !== actor.id) throw new ForbiddenException('Solo quien inició el tiempo puede detenerlo'); await tx.manufacturingAssemblyTimeLog.update({ where: { id: log.id }, data: { endedAt: new Date(), note: this.text(dto?.note) || log.note } }); await this.audit(tx, tenantId, orderId, log.id, 'ASSEMBLY_TIME_STOPPED', `${log.operation.name}: tiempo detenido`, actor, { operationId: log.operationId }); }); return this.list(orderId); }

  async addEvidence(operationId: string, dto: CreateManufacturingAssemblyEvidenceDto) { const { tenantId, userId } = this.context(); let orderId = ''; await this.prisma.$transaction(async (tx: any) => { const actor = await this.actor(tx, tenantId, userId); const operation = await this.lockedOperation(tx, tenantId, operationId, actor); orderId = operation.execution.manufacturingOrderId; const title = this.text(dto?.title); if (!title) throw new BadRequestException('El título de la evidencia es obligatorio'); if (!this.text(dto?.reference) && !this.text(dto?.url) && !this.text(dto?.notes)) throw new BadRequestException('Incluye una referencia, URL o nota de evidencia'); const evidence = await tx.manufacturingAssemblyEvidence.create({ data: { tenantId, operationId, title, reference: this.text(dto?.reference), url: this.text(dto?.url), notes: this.text(dto?.notes), createdByUserId: actor.id, createdByName: actor.name } }); await this.audit(tx, tenantId, orderId, evidence.id, 'ASSEMBLY_EVIDENCE_ADDED', `${operation.name}: evidencia agregada`, actor, { operationId, title }); }); return this.list(orderId); }
  async addConsumption(operationId: string, dto: CreateManufacturingAssemblyConsumptionDto) { const { tenantId, userId } = this.context(); let orderId = ''; await this.prisma.$transaction(async (tx: any) => { const actor = await this.actor(tx, tenantId, userId); const operation = await this.lockedOperation(tx, tenantId, operationId, actor); orderId = operation.execution.manufacturingOrderId; if (!['IN_PROGRESS', 'PAUSED'].includes(operation.status)) throw new ConflictException('La operación debe estar iniciada para registrar consumo'); const kitLineId = String(dto?.kitLineId || '').trim(); const kitLine = await tx.manufacturingKitLine.findFirst({ where: { id: kitLineId, tenantId, kitId: operation.execution.kitId } }); if (!kitLine) throw new NotFoundException('Material no pertenece al kit de esta ejecución'); const quantity = this.amount(dto?.quantity); const totals = await tx.manufacturingAssemblyConsumption.aggregate({ where: { tenantId, kitLineId }, _sum: { quantity: true } }); const available = Math.max(0, Number(kitLine.allocatedQuantity) - Number(totals._sum.quantity || 0)); if (quantity > available + 1e-9) throw new ConflictException(`Solo hay ${available} asignadas y sin consumir`); const consumption = await tx.manufacturingAssemblyConsumption.create({ data: { tenantId, operationId, kitLineId, quantity, notes: this.text(dto?.notes), consumedByUserId: actor.id, consumedByName: actor.name } }); await this.audit(tx, tenantId, orderId, consumption.id, 'ASSEMBLY_MATERIAL_CONSUMED', `${operation.name}: ${quantity} de ${kitLine.itemCodeSnapshot} consumidas`, actor, { operationId, kitLineId, quantity }); }); return this.list(orderId); }

  private async lockedOperation(tx: any, tenantId: string, operationId: string, actor: Actor) { await tx.$queryRaw`SELECT "id" FROM "ManufacturingAssemblyOperation" WHERE "id" = ${operationId} FOR UPDATE`; const operation = await tx.manufacturingAssemblyOperation.findFirst({ where: { id: operationId, tenantId }, include: { execution: { include: { manufacturingOrder: { include: { members: { where: { userId: actor.id } } } } } } } }); if (!operation) throw new NotFoundException('Operación no encontrada'); const order = operation.execution.manufacturingOrder; if (actor.role === 'TECH' && order.responsibleUserId !== actor.id && !order.members.length) throw new NotFoundException('Operación no encontrada'); if (['CANCELED', 'ON_HOLD'].includes(order.status)) throw new ConflictException('La orden no permite ejecutar ensamble'); if (['COMPLETED', 'CANCELED'].includes(operation.execution.status)) throw new ConflictException('La ejecución ya está cerrada'); return operation; }
  private async dependencies(tx: any, operation: any) { const positions = Array.isArray(operation.dependsOnPositions) ? operation.dependsOnPositions.map(Number) : []; if (!positions.length) return; const pending = await tx.manufacturingAssemblyOperation.count({ where: { executionId: operation.executionId, position: { in: positions }, status: { notIn: ['COMPLETED', 'NOT_APPLICABLE'] } } }); if (pending) throw new ConflictException('Completa las operaciones predecesoras antes de continuar'); }
  private async completeExecutionIfReady(tx: any, tenantId: string, executionId: string) { const pending = await tx.manufacturingAssemblyOperation.count({ where: { tenantId, executionId, required: true, status: { not: 'COMPLETED' } } }); if (!pending) await tx.manufacturingAssemblyExecution.update({ where: { id: executionId }, data: { status: 'COMPLETED', completedAt: new Date(), lockVersion: { increment: 1 } } }); }
  private serialize(execution: any) { const now = Date.now(); const operations = execution.operations.map((operation: any) => { const actualMinutes = operation.timeLogs.reduce((sum: number, log: any) => sum + Math.max(0, ((log.endedAt ? new Date(log.endedAt).getTime() : now) - new Date(log.startedAt).getTime()) / 60000), 0); const consumedQuantity = operation.consumptions.reduce((sum: number, item: any) => sum + Number(item.quantity), 0); return { ...operation, actualMinutes, consumedQuantity, consumptions: operation.consumptions.map((item: any) => ({ ...item, quantity: Number(item.quantity) })) }; }); return { ...execution, operations, summary: { operationCount: operations.length, completedCount: operations.filter((item: any) => ['COMPLETED', 'NOT_APPLICABLE'].includes(item.status)).length, blockedCount: operations.filter((item: any) => item.status === 'BLOCKED').length, actualMinutes: operations.reduce((sum: number, item: any) => sum + item.actualMinutes, 0), progressPercent: operations.length ? Math.round(operations.reduce((sum: number, item: any) => sum + Number(item.progressPercent), 0) / operations.length) : 0 } }; }
  private async audit(tx: any, tenantId: string, orderId: string, entityId: string, action: string, summary: string, actor: Actor, afterData: unknown) { await tx.manufacturingAuditEvent.create({ data: { tenantId, manufacturingOrderId: orderId, entityType: action === 'MANUFACTURING_ASSEMBLY_CREATED' ? 'ManufacturingAssemblyExecution' : 'ManufacturingAssemblyOperation', entityId, action, summary, actorUserId: actor.id, actorName: actor.name, afterData: JSON.parse(JSON.stringify(afterData)) } }); }
}
