-- Bootstrap mínimo de Timescale + esquema timeseries.
-- Se ejecuta SOLO en la primera inicialización de la base (cuando el volumen está vacío).

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE SCHEMA IF NOT EXISTS timeseries;

-- Tabla "compat" para que NO te explote el código actual:
-- - TelemetryService (device_id/metric/value_double)
-- - MqttService/RulesService (asset_code/sensor_type/value)
--
-- Puedes separar esto en 2 tablas más adelante; por ahora, esto evita conflictos.
CREATE TABLE IF NOT EXISTS timeseries.telemetry (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id    TEXT NOT NULL,
  ts           TIMESTAMPTZ NOT NULL,

  -- path MQTT / asset
  asset_code   TEXT,
  sensor_type  TEXT,
  value        DOUBLE PRECISION,

  -- path device / metric
  device_id    TEXT,
  metric       TEXT,
  value_double DOUBLE PRECISION,
  unit         TEXT,

  meta         JSONB DEFAULT '{}'::jsonb,
  created_at   TIMESTAMPTZ DEFAULT now(),

  PRIMARY KEY (tenant_id, ts, id)
);

-- Hypertable (ts = columna de partición)
SELECT create_hypertable('timeseries.telemetry','ts', if_not_exists => TRUE);

-- Índices para queries típicas
CREATE INDEX IF NOT EXISTS idx_ts_tenant_ts
  ON timeseries.telemetry (tenant_id, ts DESC);

CREATE INDEX IF NOT EXISTS idx_ts_mqtt_lookup
  ON timeseries.telemetry (tenant_id, asset_code, sensor_type, ts DESC);

CREATE INDEX IF NOT EXISTS idx_ts_device_lookup
  ON timeseries.telemetry (tenant_id, device_id, metric, ts DESC);

-- Unique indexes para soportar ON CONFLICT en MQTT (y futuros upserts por device)
CREATE UNIQUE INDEX IF NOT EXISTS ux_ts_mqtt
  ON timeseries.telemetry (tenant_id, asset_code, sensor_type, ts);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ts_device
  ON timeseries.telemetry (tenant_id, device_id, metric, ts);

-- Vista agregada 5m (compatible con TelemetryService bucket='5m')
CREATE OR REPLACE VIEW timeseries.v_telemetry_5m AS
SELECT
  tenant_id,
  device_id,
  metric,
  time_bucket('5 minutes', ts) AS bucket,
  avg(value_double) AS v_avg,
  max(unit) AS unit
FROM timeseries.telemetry
WHERE device_id IS NOT NULL AND metric IS NOT NULL
GROUP BY tenant_id, device_id, metric, bucket;
