CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Hypertable de telemetría
-- Nota: cualquier PK/índice único debe incluir la columna de partición (ts)
CREATE TABLE IF NOT EXISTS telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id  TEXT NOT NULL,
  asset_code TEXT NOT NULL,
  sensor_type TEXT NOT NULL,
  ts TIMESTAMPTZ NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  meta JSONB DEFAULT '{}'::jsonb,
  PRIMARY KEY (tenant_id, asset_code, sensor_type, ts, id)
);

SELECT create_hypertable('telemetry', 'ts', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS idx_telemetry_tenant_asset_ts ON telemetry(tenant_id, asset_code, ts DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_sensor_ts ON telemetry(sensor_type, ts DESC);

-- (Opcional) RLS ejemplo (desactivado por defecto)
-- ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY tenant_isolation ON telemetry USING (tenant_id = current_setting('cmms.tenant', true));
