'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiBase, apiFetch } from '@/lib/api';
import { useApiSWR } from '@/lib/swr';
import {
  dateLabel,
  engineeringDisciplineLabel,
  engineeringReleaseStatusClass,
  engineeringReleaseStatusLabel,
  type EngineeringDocument,
  type EngineeringDocumentRevision,
  type EngineeringRelease,
  type EngineeringReleaseValidation,
  type ManufacturingBom,
  type ManufacturingBomRevision,
  type ManufacturingOrder,
} from '@/lib/manufacturing';

type Auth = { token?: string; tenantSlug?: string };

export function EngineeringReleasesTab({ order, role, auth, onChanged }: { order: ManufacturingOrder; role: string; auth: Auth; onChanged: () => void | Promise<unknown> }) {
  const { data, error, isLoading, mutate } = useApiSWR<EngineeringRelease[]>(`/manufacturing/orders/${order.id}/releases`, auth.token, auth.tenantSlug);
  const { data: boms } = useApiSWR<ManufacturingBom[]>(`/manufacturing/orders/${order.id}/boms`, auth.token, auth.tenantSlug);
  const { data: documents } = useApiSWR<EngineeringDocument[]>(`/manufacturing/orders/${order.id}/documents`, auth.token, auth.tenantSlug);
  const releases = data || [];
  const draft = releases.find((release) => release.status === 'DRAFT');
  const current = releases.find((release) => release.status === 'RELEASED');
  const canManage = role === 'ADMIN' && order.status !== 'ON_HOLD' && order.status !== 'CANCELED';
  const [creating, setCreating] = useState(false);
  const [message, setMessage] = useState('');

  async function accept(next: EngineeringRelease[]) { setMessage(''); await mutate(next, { revalidate: false }); await onChanged(); }

  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Liberaciones de Ingeniería</h2><p className="text-sm text-gray-600">Paquetes constructivos inmutables que fijan BOM, planos y programas.</p></div>{canManage && !draft ? <button className="rounded bg-black px-4 py-2 text-sm text-white" onClick={() => setCreating((value) => !value)}>{creating ? 'Cerrar' : 'Nueva liberación'}</button> : null}</div>
    {order.status === 'ON_HOLD' || order.status === 'CANCELED' ? <div className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Las liberaciones quedan en consulta mientras la orden esté {order.status === 'ON_HOLD' ? 'en pausa' : 'cancelada'}.</div> : null}
    {message ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700 whitespace-pre-wrap">{message}</div> : null}
    {error ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">No se pudo cargar el historial de liberaciones.</div> : null}

    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Liberaciones publicadas" value={releases.filter((item) => ['RELEASED', 'SUPERSEDED'].includes(item.status)).length} /><Metric label="Liberación vigente" value={current?.releaseCode || '—'} tone="green" /><Metric label="BOM liberada" value={current ? `${current.bomCodeSnapshot} · ${current.bomRevisionCodeSnapshot}` : '—'} /><Metric label="Documentos vigentes" value={current?.documentCount ?? 0} tone="sky" /></div>
    {creating && canManage ? <CreateRelease order={order} releases={releases} boms={boms || []} documents={documents || []} auth={auth} onCreated={async (next) => { await accept(next); setCreating(false); }} onError={setMessage} /> : null}
    {draft ? <ReleaseBuilder release={draft} order={order} boms={boms || []} documents={documents || []} auth={auth} editable={canManage} onChanged={accept} onError={setMessage} /> : null}
    {isLoading ? <div className="py-8 text-center text-sm text-gray-500">Cargando liberaciones…</div> : null}

    <div className="space-y-3"><h3 className="font-semibold">Historial publicado</h3>{!releases.some((item) => item.status !== 'DRAFT') ? <div className="rounded-lg border border-dashed p-8 text-center text-sm text-gray-500">Todavía no hay paquetes publicados.</div> : releases.filter((item) => item.status !== 'DRAFT').map((release) => <PublishedRelease key={release.id} release={release} auth={auth} onError={setMessage} />)}</div>
  </div>;
}

function CreateRelease({ order, releases, boms, documents, auth, onCreated, onError }: { order: ManufacturingOrder; releases: EngineeringRelease[]; boms: ManufacturingBom[]; documents: EngineeringDocument[]; auth: Auth; onCreated: (items: EngineeringRelease[]) => void | Promise<void>; onError: (value: string) => void }) {
  const eligibleBoms = eligibleBomRevisions(boms);
  const defaults = defaultDocumentSelection(documents);
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ releaseCode: `LIB-${String(Math.max(0, ...releases.map((item) => item.sequence)) + 1).padStart(3, '0')}`, title: `Liberación constructiva ${order.number}`, notes: '', bomRevisionId: eligibleBoms[0]?.revision.id || '', documentRevisionIds: defaults });
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!auth.token || !auth.tenantSlug) return; setBusy(true); onError(''); try { await onCreated(await apiFetch(`/manufacturing/orders/${order.id}/releases`, { method: 'POST', token: auth.token, tenantSlug: auth.tenantSlug, body: form })); } catch (error: any) { onError(apiError(error, 'No se pudo crear la liberación')); } finally { setBusy(false); } }
  if (!eligibleBoms.length) return <div className="rounded border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Primero debe existir una revisión de BOM aprobada.</div>;
  return <form onSubmit={submit} className="space-y-4 rounded-lg border bg-gray-50 p-4"><div><h3 className="font-semibold">Crear borrador de liberación</h3><p className="text-xs text-gray-600">Se preselecciona la revisión aprobada más reciente de cada documento.</p></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Código *"><input required className="w-full rounded border px-3 py-2" value={form.releaseCode} onChange={(e) => setForm({ ...form, releaseCode: e.target.value })} /></Field><Field label="Título *"><input required className="w-full rounded border px-3 py-2" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="BOM aprobada *"><select required className="w-full rounded border px-3 py-2" value={form.bomRevisionId} onChange={(e) => setForm({ ...form, bomRevisionId: e.target.value })}>{eligibleBoms.map(({ bom, revision }) => <option key={revision.id} value={revision.id}>{bom.code} · Rev. {revision.revisionCode} · {revision.lineCount} líneas</option>)}</select></Field><Field label="Motivo"><input className="w-full rounded border px-3 py-2" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field></div><DocumentSelector documents={documents} selected={form.documentRevisionIds} onChange={(documentRevisionIds) => setForm({ ...form, documentRevisionIds })} /><div className="flex justify-end"><button disabled={busy} className="rounded bg-black px-4 py-2 text-sm text-white">{busy ? 'Creando…' : 'Crear borrador'}</button></div></form>;
}

function ReleaseBuilder({ release, order, boms, documents, auth, editable, onChanged, onError }: { release: EngineeringRelease; order: ManufacturingOrder; boms: ManufacturingBom[]; documents: EngineeringDocument[]; auth: Auth; editable: boolean; onChanged: (items: EngineeringRelease[]) => void | Promise<void>; onError: (value: string) => void }) {
  const [form, setForm] = useState(() => releaseForm(release));
  const [validation, setValidation] = useState<EngineeringReleaseValidation | null>(null);
  const [busy, setBusy] = useState(false);
  const [dirty, setDirty] = useState(false);
  useEffect(() => { setForm(releaseForm(release)); setDirty(false); }, [release]);
  const eligibleBoms = eligibleBomRevisions(boms);
  function update(patch: Partial<typeof form>) { setForm((current) => ({ ...current, ...patch })); setDirty(true); setValidation(null); }
  async function save() { if (!auth.token || !auth.tenantSlug) return; setBusy(true); onError(''); try { const next = await apiFetch<EngineeringRelease[]>(`/manufacturing/orders/${order.id}/releases/${release.id}`, { method: 'PATCH', token: auth.token, tenantSlug: auth.tenantSlug, body: { ...form, lockVersion: release.lockVersion } }); await onChanged(next); setValidation(null); } catch (error: any) { onError(apiError(error, 'No se pudo guardar el borrador')); } finally { setBusy(false); } }
  async function validateRelease() { if (!auth.token || !auth.tenantSlug || dirty) return; setBusy(true); onError(''); try { setValidation(await apiFetch(`/manufacturing/orders/${order.id}/releases/${release.id}/validate`, { token: auth.token, tenantSlug: auth.tenantSlug })); } catch (error: any) { onError(apiError(error, 'No se pudo validar el paquete')); } finally { setBusy(false); } }
  async function publish() { if (!auth.token || !auth.tenantSlug || !validation?.valid) return; if (!form.notes.trim() || form.notes.trim().length < 5) { onError('Escribe un motivo de liberación de al menos 5 caracteres.'); return; } if (!window.confirm(`¿Publicar ${release.releaseCode}? El paquete quedará inmutable.`)) return; setBusy(true); onError(''); try { await onChanged(await apiFetch(`/manufacturing/orders/${order.id}/releases/${release.id}/publish`, { method: 'POST', token: auth.token, tenantSlug: auth.tenantSlug, body: { lockVersion: release.lockVersion, notes: form.notes } })); } catch (error: any) { onError(apiError(error, 'No se pudo publicar la liberación')); } finally { setBusy(false); } }
  return <div className="rounded-lg border border-sky-200 bg-white"><div className="flex flex-wrap items-start justify-between gap-3 border-b bg-sky-50 p-4"><div><div className="flex items-center gap-2"><h3 className="font-semibold">Borrador {release.releaseCode}</h3><span className="rounded-full bg-gray-200 px-2 py-0.5 text-xs">v{release.lockVersion}</span></div><p className="mt-1 text-sm text-gray-600">Configura, guarda, valida y publica el paquete.</p></div>{editable ? <div className="flex gap-2"><button disabled={!dirty || busy} className="rounded border bg-white px-3 py-1.5 text-sm disabled:opacity-40" onClick={save}>Guardar</button><button disabled={dirty || busy} className="rounded border bg-white px-3 py-1.5 text-sm disabled:opacity-40" onClick={validateRelease}>Validar</button><button disabled={!validation?.valid || dirty || busy} className="rounded bg-black px-3 py-1.5 text-sm text-white disabled:opacity-40" onClick={publish}>Publicar</button></div> : null}</div>
    <div className="space-y-4 p-4"><div className="grid gap-3 md:grid-cols-3"><Field label="Título"><input disabled={!editable} className="w-full rounded border px-3 py-2 disabled:bg-gray-50" value={form.title} onChange={(e) => update({ title: e.target.value })} /></Field><Field label="BOM"><select disabled={!editable} className="w-full rounded border px-3 py-2 disabled:bg-gray-50" value={form.bomRevisionId} onChange={(e) => update({ bomRevisionId: e.target.value })}>{eligibleBoms.map(({ bom, revision }) => <option key={revision.id} value={revision.id}>{bom.code} · Rev. {revision.revisionCode} · {revision.lineCount} líneas</option>)}</select></Field><Field label="Motivo de liberación"><input disabled={!editable} className="w-full rounded border px-3 py-2 disabled:bg-gray-50" value={form.notes} onChange={(e) => update({ notes: e.target.value })} /></Field></div><DocumentSelector documents={documents} selected={form.documentRevisionIds} disabled={!editable} onChange={(documentRevisionIds) => update({ documentRevisionIds })} />{validation ? <ValidationResult validation={validation} /> : <div className="rounded border border-dashed p-3 text-sm text-gray-500">Guarda los cambios y ejecuta la validación antes de publicar.</div>}</div>
  </div>;
}

function DocumentSelector({ documents, selected, onChange, disabled = false }: { documents: EngineeringDocument[]; selected: string[]; onChange: (ids: string[]) => void; disabled?: boolean }) {
  function choose(document: EngineeringDocument, revisionId: string) { const documentRevisionIds = new Set(document.revisions.map((revision) => revision.id)); onChange([...selected.filter((id) => !documentRevisionIds.has(id)), ...(revisionId ? [revisionId] : [])]); }
  return <div><div className="mb-2 text-sm font-medium">Revisión por documento</div><div className="grid gap-2 md:grid-cols-2">{documents.filter((document) => document.active).map((document) => { const eligible = document.revisions.filter((revision) => ['APPROVED', 'RELEASED'].includes(revision.status)); const value = eligible.find((revision) => selected.includes(revision.id))?.id || ''; return <div key={document.id} className="rounded border p-3"><div className="mb-2 flex items-center justify-between gap-2"><div><div className="text-sm font-medium">{document.code} · {document.name}</div><div className="text-xs text-gray-500">{engineeringDisciplineLabel[document.discipline]}</div></div>{!eligible.length ? <span className="text-xs text-red-700">Sin revisión aprobada</span> : null}</div><select disabled={disabled || !eligible.length} className="w-full rounded border px-3 py-2 text-sm disabled:bg-gray-50" value={value} onChange={(e) => choose(document, e.target.value)}><option value="">No incluir</option>{eligible.map((revision) => <option key={revision.id} value={revision.id}>Rev. {revision.revisionCode} · {revision.status === 'RELEASED' ? 'Liberada' : 'Aprobada'}</option>)}</select></div>; })}</div></div>;
}

function ValidationResult({ validation }: { validation: EngineeringReleaseValidation }) { return <div className={`rounded border p-4 ${validation.valid ? 'border-emerald-200 bg-emerald-50' : 'border-red-200 bg-red-50'}`}><div className="font-medium">{validation.valid ? 'Paquete listo para publicar' : 'El paquete tiene errores bloqueantes'}</div><div className="mt-1 text-sm">{validation.summary.bomCode} · Rev. {validation.summary.bomRevisionCode} · {validation.summary.bomLineCount} líneas · {validation.summary.documentCount} documentos</div>{validation.errors.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-red-800">{validation.errors.map((issue, index) => <li key={`${issue.code}-${index}`}>{issue.message}</li>)}</ul> : null}{validation.warnings.length ? <div className="mt-3 rounded border border-amber-200 bg-amber-50 p-3"><div className="text-sm font-medium text-amber-900">Advertencias</div><ul className="mt-1 list-disc pl-5 text-sm text-amber-800">{validation.warnings.map((issue, index) => <li key={`${issue.code}-${index}`}>{issue.message}</li>)}</ul></div> : null}</div>; }

function PublishedRelease({ release, auth, onError }: { release: EngineeringRelease; auth: Auth; onError: (value: string) => void }) {
  const [expanded, setExpanded] = useState(release.status === 'RELEASED');
  return <article className="rounded-lg border"><div className="flex flex-wrap items-start justify-between gap-3 p-4"><div><div className="flex items-center gap-2"><strong>{release.releaseCode} · {release.title}</strong><span className={`rounded-full px-2 py-0.5 text-xs ${engineeringReleaseStatusClass[release.status]}`}>{engineeringReleaseStatusLabel[release.status]}</span></div><div className="mt-1 text-xs text-gray-500">Publicada por {release.releasedByName || '—'} · {dateLabel(release.releasedAt, true)} · {release.documentCount} documentos</div>{release.notes ? <p className="mt-2 text-sm">{release.notes}</p> : null}</div><button className="rounded border px-3 py-1.5 text-sm" onClick={() => setExpanded((value) => !value)}>{expanded ? 'Ocultar' : 'Ver contenido'}</button></div>{expanded ? <div className="border-t bg-gray-50 p-4"><div className="mb-3 rounded border bg-white p-3"><div className="text-xs text-gray-500">BOM fijada</div><div className="font-medium">{release.bomCodeSnapshot} · Rev. {release.bomRevisionCodeSnapshot}</div><div className="text-xs text-gray-500">{release.bomLineCountSnapshot} líneas</div></div><div className="grid gap-2 md:grid-cols-2">{release.documents.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded border bg-white p-3"><div><div className="text-sm font-medium">{item.documentCodeSnapshot} · Rev. {item.revisionCodeSnapshot}</div><div className="text-xs text-gray-500">{item.documentNameSnapshot} · {engineeringDisciplineLabel[item.disciplineSnapshot]}</div></div><button className="text-sm underline" onClick={() => openAttachment(item.documentRevision.fileAttachment.id, auth, onError)}>Archivo</button></div>)}</div>{release.validationSnapshot?.warnings?.length ? <div className="mt-3 text-xs text-amber-800">Publicada con {release.validationSnapshot.warnings.length} advertencia(s) registradas.</div> : null}</div> : null}</article>;
}

function eligibleBomRevisions(boms: ManufacturingBom[]) { return boms.flatMap((bom) => bom.revisions.filter((revision) => ['APPROVED', 'RELEASED'].includes(revision.status)).map((revision) => ({ bom, revision }))).sort((a, b) => b.revision.sequence - a.revision.sequence); }
function defaultDocumentSelection(documents: EngineeringDocument[]) { return documents.filter((document) => document.active).map((document) => document.revisions.find((revision) => ['APPROVED', 'RELEASED'].includes(revision.status))?.id).filter((id): id is string => !!id); }
function releaseForm(release: EngineeringRelease) { return { title: release.title, notes: release.notes || '', bomRevisionId: release.bomRevisionId, documentRevisionIds: release.documents.map((item) => item.documentRevisionId) }; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1 text-sm"><span className="text-gray-600">{label}</span>{children}</label>; }
function Metric({ label, value, tone = 'gray' }: { label: string; value: string | number; tone?: 'gray' | 'sky' | 'green' }) { const color = { gray: 'text-gray-900', sky: 'text-sky-700', green: 'text-emerald-700' }[tone]; return <div className="rounded-lg border p-3"><div className="text-xs text-gray-500">{label}</div><div className={`mt-1 text-lg font-semibold ${color}`}>{value}</div></div>; }
function apiError(error: any, fallback: string) { const message = String(error?.message || ''); try { const start = message.indexOf('{'); if (start >= 0) { const parsed = JSON.parse(message.slice(start)); if (parsed?.errors) return [parsed.message, ...parsed.errors.map((item: any) => item.message)].filter(Boolean).join('\n'); return Array.isArray(parsed.message) ? parsed.message.join('\n') : parsed.message || fallback; } } catch {} return message || fallback; }
async function openAttachment(id: string, auth: Auth, onError: (value: string) => void) { if (!auth.token || !auth.tenantSlug) return; const popup = window.open('', '_blank'); try { const response = await fetch(`${apiBase}/attachments/${encodeURIComponent(id)}/view`, { headers: { Authorization: `Bearer ${auth.token}`, 'x-tenant': auth.tenantSlug } }); if (!response.ok) throw new Error(await response.text()); const url = URL.createObjectURL(await response.blob()); if (popup) popup.location.href = url; else window.open(url, '_blank'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } catch (error: any) { popup?.close(); onError(apiError(error, 'No se pudo abrir el archivo')); } }
