'use client';

import { useState } from 'react';
import { apiFetch } from '@/lib/api';
import { useApiSWR } from '@/lib/swr';
import { SignatureCanvas } from '@/components/SignatureCanvas';
import { dateLabel, localDateInput, type ManufacturingHandover, type ManufacturingHandoverDocument, type ManufacturingOrder } from '@/lib/manufacturing';

type Auth = { token?: string; tenantSlug?: string };
const statusLabel: Record<string, string> = { DRAFT: 'En preparación', READY_FOR_DELIVERY: 'Lista para entrega', CLOSED: 'Entregada y cerrada', CANCELED: 'Cancelada' };

export function ManufacturingHandoverTab({ order, role, auth, onChanged }: { order: ManufacturingOrder; role: string; auth: Auth; onChanged: () => Promise<any> | any }) {
  const { data, error, isLoading, mutate } = useApiSWR<ManufacturingHandover[]>(`/manufacturing/orders/${order.id}/handovers`, auth.token, auth.tenantSlug);
  const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
  const handovers = data || []; const eligible = (order.units || []).filter((unit) => unit.status === 'COMMISSIONED' && !handovers.some((item) => item.manufacturedUnitId === unit.id));

  async function action(path: string, method: 'POST' | 'PATCH' | 'DELETE', body?: any, key = path) {
    if (!auth.token || !auth.tenantSlug) return; setBusy(key); setMessage('');
    try { const next = await apiFetch<ManufacturingHandover[]>(path, { method, token: auth.token, tenantSlug: auth.tenantSlug, body }); await mutate(next, { revalidate: false }); await onChanged(); }
    catch (err: any) { setMessage(err?.message || 'No se pudo actualizar el expediente'); }
    finally { setBusy(''); }
  }

  return <div className="space-y-4">
    <div><h2 className="text-lg font-semibold">Expediente y entrega final</h2><p className="text-sm text-gray-600">Consolida as-built, manuales, respaldos, FAT/SAT, garantía, capacitación y repuestos antes de transferir la máquina a mantenimiento.</p></div>
    {message ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</div> : null}
    {error ? <div className="text-sm text-red-700">No se pudieron cargar los expedientes.</div> : null}
    {isLoading ? <div className="text-sm text-gray-500">Cargando entrega final…</div> : null}
    {role === 'ADMIN' && eligible.length ? <div className="rounded-lg border border-violet-200 bg-violet-50 p-4"><strong>Unidades listas para expediente</strong><div className="mt-3 flex flex-wrap gap-2">{eligible.map((unit) => <button key={unit.id} disabled={!!busy} className="rounded bg-violet-700 px-3 py-2 text-sm text-white disabled:opacity-40" onClick={() => action(`/manufacturing/units/${unit.id}/handovers`, 'POST', { trainingRequired: true }, `create:${unit.id}`)}>Crear entrega · Unidad {unit.unitNumber}</button>)}</div></div> : null}
    {!isLoading && !handovers.length ? <div className="rounded-lg border border-dashed p-8 text-center text-sm text-gray-500">El expediente estará disponible cuando una unidad tenga SAT completamente aceptado.</div> : null}
    {handovers.map((handover) => <HandoverCard key={handover.id} handover={handover} role={role} busy={busy} action={action} />)}
  </div>;
}

function HandoverCard({ handover, role, busy, action }: { handover: ManufacturingHandover; role: string; busy: string; action: (path: string, method: 'POST' | 'PATCH' | 'DELETE', body?: any, key?: string) => Promise<void> }) {
  const editable = handover.status === 'DRAFT';
  return <section className="rounded-lg border bg-white p-4 space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{handover.handoverCode} · Unidad {handover.manufacturedUnit.unitNumber}</div><div className="text-sm text-gray-600">{handover.asset.code} · {handover.asset.name} · SAT {handover.satExecution.executionCode}</div></div><span className={`rounded-full px-3 py-1 text-xs ${handover.status === 'CLOSED' ? 'bg-violet-100 text-violet-800' : handover.status === 'READY_FOR_DELIVERY' ? 'bg-emerald-100 text-emerald-800' : 'bg-gray-100 text-gray-800'}`}>{statusLabel[handover.status]}</span></div>
    <div className="grid grid-cols-2 gap-2 md:grid-cols-5"><Metric label="Avance documental" value={`${handover.summary.progressPercent}%`} /><Metric label="Documentos" value={`${handover.summary.providedCount}/${handover.summary.documentCount}`} /><Metric label="Omitidos" value={String(handover.summary.waivedCount)} /><Metric label="Capacitación" value={handover.summary.trainingComplete ? 'Completa' : 'Pendiente'} /><Metric label="Transferencia" value={handover.summary.transferredToMaintenance ? 'Realizada' : 'Pendiente'} /></div>
    <div><h3 className="mb-2 font-medium">Dossier documental</h3><div className="space-y-2">{handover.documents.map((document) => <DocumentRow key={document.id} document={document} editable={editable} canWaive={role === 'ADMIN'} busy={busy} action={action} />)}</div></div>
    <div className="grid gap-4 lg:grid-cols-2">
      <div className="space-y-2"><h3 className="font-medium">Capacitación</h3>{handover.trainings.map((item) => <div key={item.id} className="rounded border p-3 text-sm"><div className="flex justify-between gap-2"><strong>{item.topic}</strong>{editable ? <button className="text-xs text-red-700" onClick={() => action(`/manufacturing/handover-trainings/${item.id}`, 'DELETE')}>Eliminar</button> : null}</div><div className="text-gray-600">{dateLabel(item.deliveredAt)} · {item.durationHours} h · {item.attendeeCount} asistentes</div><div className="text-xs text-gray-500">Instructor: {item.instructorName} · Cliente: {item.clientContactName} · Evidencia: {item.evidenceReference}</div></div>)}{editable ? <TrainingForm handoverId={handover.id} busy={busy} action={action} /> : null}</div>
      <div className="space-y-2"><h3 className="font-medium">Repuestos recomendados</h3>{handover.spares.map((item) => <div key={item.id} className="rounded border p-3 text-sm"><div className="flex justify-between gap-2"><strong>{item.itemCode ? `${item.itemCode} · ` : ''}{item.description}</strong>{editable ? <button className="text-xs text-red-700" onClick={() => action(`/manufacturing/handover-spares/${item.id}`, 'DELETE')}>Eliminar</button> : null}</div><div className="text-gray-600">Entrega: {item.quantity} {item.unit}{item.recommendedStock !== null && item.recommendedStock !== undefined ? ` · Stock recomendado: ${item.recommendedStock}` : ''}</div></div>)}{editable ? <SpareForm handoverId={handover.id} busy={busy} action={action} /> : null}</div>
    </div>
    {editable && role === 'ADMIN' ? <div className="flex justify-end"><button disabled={!!busy || handover.summary.pendingRequiredCount > 0 || !handover.summary.trainingComplete} className="rounded bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-40" onClick={() => action(`/manufacturing/handovers/${handover.id}/ready`, 'POST', { lockVersion: handover.lockVersion })}>Liberar expediente para firma</button></div> : null}
    {handover.status === 'READY_FOR_DELIVERY' && role === 'ADMIN' ? <AcceptanceForm handover={handover} busy={busy} action={action} /> : null}
    {handover.acceptance ? <div className="rounded border border-violet-200 bg-violet-50 p-4 text-sm"><strong>Acta aceptada por {handover.acceptance.clientName}</strong><div>{handover.acceptance.clientRole}{handover.acceptance.clientCompany ? ` · ${handover.acceptance.clientCompany}` : ''}</div><div className="text-xs text-gray-600">Entregó {handover.acceptance.deliveredByName} · {dateLabel(handover.acceptance.signedAt, true)}</div></div> : null}
  </section>;
}

function DocumentRow({ document, editable, canWaive, busy, action }: { document: ManufacturingHandoverDocument; editable: boolean; canWaive: boolean; busy: string; action: any }) {
  const [status, setStatus] = useState(document.status); const [reference, setReference] = useState(document.reference || ''); const [url, setUrl] = useState(document.url || ''); const [revision, setRevision] = useState(document.revision || ''); const [waiverReason, setWaiverReason] = useState(document.waiverReason || '');
  return <div className="rounded border p-3"><div className="grid gap-2 md:grid-cols-[minmax(220px,1fr)_150px_1fr_100px_auto] md:items-center"><div><div className="text-sm font-medium">{document.position}. {document.name}</div><div className="text-xs text-gray-500">{document.required ? 'Obligatorio' : 'Opcional'}{document.providedByName ? ` · ${document.providedByName}` : ''}</div></div><select disabled={!editable} className="rounded border px-2 py-2 text-sm disabled:bg-gray-50" value={status} onChange={(event) => setStatus(event.target.value as any)}><option value="PENDING">Pendiente</option><option value="PROVIDED">Entregado</option>{canWaive || status === 'WAIVED' ? <option value="WAIVED">No aplica</option> : null}</select><input disabled={!editable} className="rounded border px-2 py-2 text-sm disabled:bg-gray-50" placeholder={status === 'WAIVED' ? 'Justificación' : 'Referencia documental'} value={status === 'WAIVED' ? waiverReason : reference} onChange={(event) => status === 'WAIVED' ? setWaiverReason(event.target.value) : setReference(event.target.value)} /><input disabled={!editable} className="rounded border px-2 py-2 text-sm disabled:bg-gray-50" placeholder="Rev." value={revision} onChange={(event) => setRevision(event.target.value)} />{editable ? <button disabled={!!busy} className="rounded border px-3 py-2 text-sm" onClick={() => action(`/manufacturing/handover-documents/${document.id}`, 'PATCH', { status, reference, url, revision, waiverReason, lockVersion: document.lockVersion })}>Guardar</button> : null}</div>{editable && status === 'PROVIDED' ? <input className="mt-2 w-full rounded border px-2 py-2 text-sm" placeholder="Enlace o ubicación opcional" value={url} onChange={(event) => setUrl(event.target.value)} /> : document.url ? <div className="mt-1 text-xs text-blue-700">{document.url}</div> : null}</div>;
}

function TrainingForm({ handoverId, busy, action }: { handoverId: string; busy: string; action: any }) {
  const [form, setForm] = useState({ topic: '', deliveredAt: localDateInput(new Date().toISOString()), durationHours: '2', instructorName: '', clientContactName: '', attendeeCount: '1', evidenceReference: '' }); const field = (name: string, value: string) => setForm((current) => ({ ...current, [name]: value }));
  return <div className="rounded border border-dashed p-3 space-y-2"><div className="grid grid-cols-2 gap-2"><input className="col-span-2 rounded border px-2 py-2 text-sm" placeholder="Tema" value={form.topic} onChange={(e) => field('topic', e.target.value)} /><input type="date" className="rounded border px-2 py-2 text-sm" value={form.deliveredAt} onChange={(e) => field('deliveredAt', e.target.value)} /><input type="number" min="0.25" step="0.25" className="rounded border px-2 py-2 text-sm" placeholder="Horas" value={form.durationHours} onChange={(e) => field('durationHours', e.target.value)} /><input className="rounded border px-2 py-2 text-sm" placeholder="Instructor" value={form.instructorName} onChange={(e) => field('instructorName', e.target.value)} /><input className="rounded border px-2 py-2 text-sm" placeholder="Contacto cliente" value={form.clientContactName} onChange={(e) => field('clientContactName', e.target.value)} /><input type="number" min="1" className="rounded border px-2 py-2 text-sm" placeholder="Asistentes" value={form.attendeeCount} onChange={(e) => field('attendeeCount', e.target.value)} /><input className="rounded border px-2 py-2 text-sm" placeholder="Evidencia / acta" value={form.evidenceReference} onChange={(e) => field('evidenceReference', e.target.value)} /></div><button disabled={!!busy} className="rounded border px-3 py-2 text-sm" onClick={() => action(`/manufacturing/handovers/${handoverId}/trainings`, 'POST', form)}>Registrar capacitación</button></div>;
}

function SpareForm({ handoverId, busy, action }: { handoverId: string; busy: string; action: any }) {
  const [form, setForm] = useState({ itemCode: '', description: '', quantity: '1', unit: 'UND', recommendedStock: '' }); const field = (name: string, value: string) => setForm((current) => ({ ...current, [name]: value }));
  return <div className="rounded border border-dashed p-3 space-y-2"><div className="grid grid-cols-2 gap-2"><input className="rounded border px-2 py-2 text-sm" placeholder="Código" value={form.itemCode} onChange={(e) => field('itemCode', e.target.value)} /><input className="rounded border px-2 py-2 text-sm" placeholder="Descripción" value={form.description} onChange={(e) => field('description', e.target.value)} /><input type="number" min="0.000001" step="any" className="rounded border px-2 py-2 text-sm" placeholder="Cantidad" value={form.quantity} onChange={(e) => field('quantity', e.target.value)} /><input className="rounded border px-2 py-2 text-sm" placeholder="Unidad" value={form.unit} onChange={(e) => field('unit', e.target.value)} /><input type="number" min="0" step="any" className="col-span-2 rounded border px-2 py-2 text-sm" placeholder="Stock recomendado" value={form.recommendedStock} onChange={(e) => field('recommendedStock', e.target.value)} /></div><button disabled={!!busy} className="rounded border px-3 py-2 text-sm" onClick={() => action(`/manufacturing/handovers/${handoverId}/spares`, 'POST', form)}>Agregar repuesto</button></div>;
}

function AcceptanceForm({ handover, busy, action }: { handover: ManufacturingHandover; busy: string; action: any }) {
  const [clientName, setClientName] = useState(''); const [clientRole, setClientRole] = useState(''); const [clientCompany, setClientCompany] = useState(''); const [comments, setComments] = useState(''); const [signature, setSignature] = useState<string | null>('');
  return <div className="space-y-3 rounded border border-emerald-300 bg-emerald-50 p-4"><div><strong>Acta formal de entrega</strong><p className="text-xs text-gray-600">La firma cierra el expediente, transfiere el activo a mantenimiento y puede completar la orden.</p></div><div className="grid gap-2 md:grid-cols-3"><input className="rounded border px-3 py-2 text-sm" placeholder="Nombre del cliente" value={clientName} onChange={(e) => setClientName(e.target.value)} /><input className="rounded border px-3 py-2 text-sm" placeholder="Cargo" value={clientRole} onChange={(e) => setClientRole(e.target.value)} /><input className="rounded border px-3 py-2 text-sm" placeholder="Empresa" value={clientCompany} onChange={(e) => setClientCompany(e.target.value)} /></div><textarea className="min-h-16 w-full rounded border px-3 py-2 text-sm" placeholder="Comentarios de entrega" value={comments} onChange={(e) => setComments(e.target.value)} /><SignatureCanvas label="Firma de recibido del cliente" initialDataUrl={signature} disabled={!!busy} onChange={setSignature} /><div className="flex justify-end"><button disabled={!!busy || !clientName || !clientRole || !signature} className="rounded bg-violet-700 px-4 py-2 text-sm text-white disabled:opacity-40" onClick={() => action(`/manufacturing/handovers/${handover.id}/acceptance`, 'POST', { clientName, clientRole, clientCompany, clientSignature: signature, comments, lockVersion: handover.lockVersion })}>Firmar, transferir y cerrar</button></div></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded border bg-gray-50 p-2"><div className="text-xs text-gray-500">{label}</div><div className="font-medium">{value}</div></div>; }
