'use client';

import { useMemo, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { useApiSWR } from '@/lib/swr';
import {
  criticalityLabel,
  dateLabel,
  supplyPlanStatusLabel,
  supplyRequirementStatusClass,
  supplyRequirementStatusLabel,
  supplyTypeLabel,
  type ManufacturingOrder,
  type ManufacturingSupplyPlan,
  type ManufacturingSupplyRequirement,
  type ManufacturingSupplyRequirementStatus,
  type SupplyType,
} from '@/lib/manufacturing';

type Auth = { token?: string; tenantSlug?: string };

export function ManufacturingSupplyTab({ order, role, auth, onChanged }: { order: ManufacturingOrder; role: string; auth: Auth; onChanged: () => void | Promise<unknown> }) {
  const { data, error, isLoading, mutate } = useApiSWR<ManufacturingSupplyPlan[]>(`/manufacturing/orders/${order.id}/supply-plans`, auth.token, auth.tenantSlug);
  const plans = data || [];
  const currentPlan = plans.find((plan) => plan.isCurrentRelease && ['ACTIVE', 'COMPLETED'].includes(plan.status));
  const canManage = role === 'ADMIN' && order.status !== 'ON_HOLD' && order.status !== 'CANCELED';
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');

  async function generate() { if (!auth.token || !auth.tenantSlug) return; setBusy(true); setMessage(''); try { const next = await apiFetch<ManufacturingSupplyPlan[]>(`/manufacturing/orders/${order.id}/supply-plans/generate`, { method: 'POST', token: auth.token, tenantSlug: auth.tenantSlug, body: {} }); await mutate(next, { revalidate: false }); await onChanged(); } catch (error: any) { setMessage(apiError(error, 'No se pudo generar el plan')); } finally { setBusy(false); } }
  async function accept(next: ManufacturingSupplyPlan[]) { setMessage(''); await mutate(next, { revalidate: false }); await onChanged(); }

  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Plan de abastecimiento</h2><p className="text-sm text-gray-600">Necesidades calculadas desde la BOM liberada, sin afectar todavía las existencias.</p></div>{canManage && order.status === 'RELEASED' && !currentPlan ? <button disabled={busy} className="rounded bg-black px-4 py-2 text-sm text-white" onClick={generate}>{busy ? 'Generando…' : 'Generar desde liberación vigente'}</button> : null}</div>
    {message ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700 whitespace-pre-wrap">{message}</div> : null}
    {error ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">No se pudieron cargar los planes de abastecimiento.</div> : null}
    {isLoading ? <div className="py-8 text-center text-sm text-gray-500">Cargando abastecimiento…</div> : null}
    {!isLoading && order.status !== 'RELEASED' && !currentPlan ? <div className="rounded border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">La orden necesita una liberación de Ingeniería vigente antes de calcular materiales.</div> : null}
    {!isLoading && order.status === 'RELEASED' && !currentPlan && plans.length ? <div className="rounded border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">La liberación cambió y el plan anterior quedó histórico. Genera un nuevo plan para la liberación vigente.</div> : null}
    {!isLoading && order.status === 'RELEASED' && !currentPlan && !plans.length ? <div className="rounded-lg border border-dashed p-10 text-center"><div className="font-medium">Aún no hay planificación de materiales</div><p className="mt-1 text-sm text-gray-600">Genera el plan desde la BOM fijada en {order.metrics.currentEngineeringReleaseCode || 'la liberación vigente'}.</p></div> : null}
    {currentPlan ? <SupplyPlanDetail plan={currentPlan} auth={auth} editable={canManage && currentPlan.status === 'ACTIVE'} onChanged={accept} onError={setMessage} /> : null}
    {plans.some((plan) => plan.id !== currentPlan?.id) ? <div className="space-y-2"><h3 className="font-semibold">Planes históricos</h3>{plans.filter((plan) => plan.id !== currentPlan?.id).map((plan) => <div key={plan.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3 text-sm"><div><strong>{plan.releaseCodeSnapshot}</strong> · {plan.bomCodeSnapshot} Rev. {plan.bomRevisionCodeSnapshot}<div className="text-xs text-gray-500">Generado por {plan.generatedByName} · {dateLabel(plan.generatedAt, true)}</div></div><div className="text-right"><div>{supplyPlanStatusLabel[plan.status]}</div><div className="text-xs text-gray-500">{plan.summary.fulfilledCount}/{plan.summary.includedCount} cubiertas</div></div></div>)}</div> : null}
  </div>;
}

function SupplyPlanDetail({ plan, auth, editable, onChanged, onError }: { plan: ManufacturingSupplyPlan; auth: Auth; editable: boolean; onChanged: (items: ManufacturingSupplyPlan[]) => void | Promise<void>; onError: (value: string) => void }) {
  const [q, setQ] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState('');
  const filtered = useMemo(() => plan.requirements.filter((item) => (!q.trim() || `${item.itemCodeSnapshot} ${item.descriptionSnapshot} ${item.supplier || ''} ${item.externalReference || ''}`.toLowerCase().includes(q.trim().toLowerCase())) && (!type || item.plannedSupplyType === type) && (!status || item.status === status)), [plan.requirements, q, type, status]);
  return <div className="space-y-4"><div className="rounded-lg border"><div className="flex flex-wrap items-start justify-between gap-3 border-b p-4"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{plan.releaseCodeSnapshot} · {plan.bomCodeSnapshot} Rev. {plan.bomRevisionCodeSnapshot}</h3><span className={`rounded-full px-2 py-0.5 text-xs ${plan.status === 'ACTIVE' ? 'bg-sky-100 text-sky-800' : 'bg-emerald-100 text-emerald-800'}`}>{supplyPlanStatusLabel[plan.status]}</span></div><p className="mt-1 text-xs text-gray-500">Fotografía generada {dateLabel(plan.generatedAt, true)} · OF de {plan.orderQuantitySnapshot} máquina(s)</p></div><div className="text-sm text-gray-600">{plan.summary.fulfilledCount}/{plan.summary.includedCount} necesidades cubiertas</div></div><div className="grid grid-cols-2 gap-3 bg-gray-50 p-3 md:grid-cols-4 lg:grid-cols-6"><Metric label="Pendientes" value={plan.summary.openCount} tone="amber" /><Metric label="Cubiertas" value={plan.summary.fulfilledCount} tone="green" /><Metric label="Cobertura stock" value={fmt(plan.summary.stockCoveredQuantity)} /><Metric label="Por comprar" value={fmt(plan.summary.buyQuantity)} /><Metric label="Por fabricar" value={fmt(plan.summary.makeQuantity)} /><Metric label="Por tercero" value={fmt(plan.summary.subcontractQuantity)} /></div></div>
    <div className="flex flex-wrap gap-2 rounded border p-3"><input className="min-w-64 flex-1 rounded border px-3 py-2 text-sm" placeholder="Buscar código, descripción, proveedor o referencia…" value={q} onChange={(e) => setQ(e.target.value)} /><select className="rounded border px-3 py-2 text-sm" value={type} onChange={(e) => setType(e.target.value)}><option value="">Todos los suministros</option>{Object.entries(supplyTypeLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select className="rounded border px-3 py-2 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos los estados</option>{Object.entries(supplyRequirementStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    <div className="space-y-2">{!filtered.length ? <div className="rounded border p-8 text-center text-sm text-gray-500">No hay necesidades para estos filtros.</div> : filtered.map((requirement) => <RequirementRow key={requirement.id} requirement={requirement} auth={auth} editable={editable} onChanged={onChanged} onError={onError} />)}</div>
  </div>;
}

function RequirementRow({ requirement, auth, editable, onChanged, onError }: { requirement: ManufacturingSupplyRequirement; auth: Auth; editable: boolean; onChanged: (items: ManufacturingSupplyPlan[]) => void | Promise<void>; onError: (value: string) => void }) {
  const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [form, setForm] = useState(() => requirementForm(requirement));
  async function save() { if (!auth.token || !auth.tenantSlug) return; setBusy(true); onError(''); try { await onChanged(await apiFetch(`/manufacturing/supply-requirements/${requirement.id}`, { method: 'PATCH', token: auth.token, tenantSlug: auth.tenantSlug, body: { ...form, lockVersion: requirement.lockVersion, fulfilledQuantity: Number(form.fulfilledQuantity), expectedAt: form.expectedAt || null } })); setEditing(false); } catch (error: any) { onError(apiError(error, 'No se pudo actualizar la necesidad')); } finally { setBusy(false); } }
  const pending = Math.max(0, requirement.requiredQuantity - requirement.fulfilledQuantity);
  return <div className={`rounded-lg border ${!requirement.included ? 'bg-gray-50 opacity-75' : 'bg-white'}`}><div className="grid gap-3 p-4 md:grid-cols-[80px_1fr_120px_120px_130px_auto]"><div><div className="text-xs text-gray-500">Posición</div><div className="font-semibold" style={{ paddingLeft: `${Math.min(requirement.levelSnapshot, 4) * 8}px` }}>{requirement.positionSnapshot}</div></div><div><div className="flex flex-wrap items-center gap-2"><strong>{requirement.itemCodeSnapshot}</strong>{requirement.isOptionalSnapshot ? <span className="rounded bg-violet-100 px-2 py-0.5 text-xs text-violet-800">Opcional</span> : null}<span className={`rounded-full px-2 py-0.5 text-xs ${supplyRequirementStatusClass[requirement.status]}`}>{supplyRequirementStatusLabel[requirement.status]}</span></div><div className="text-sm text-gray-700">{requirement.descriptionSnapshot}</div><div className="mt-1 text-xs text-gray-500">{criticalityLabel[requirement.criticalitySnapshot]} · Ingeniería: {supplyTypeLabel[requirement.engineeringSupplyType]}{requirement.inventoryItem ? ` · Inventario ${requirement.inventoryItem.sku}` : ' · Sin vínculo de inventario'}</div></div><Quantity label="Requerida" value={requirement.requiredQuantity} uom={requirement.uomSnapshot} /><Quantity label="Cubierta" value={requirement.fulfilledQuantity} uom={requirement.uomSnapshot} tone="green" /><Quantity label="Pendiente" value={pending} uom={requirement.uomSnapshot} tone={pending ? 'amber' : 'green'} /><div>{editable ? <button className="rounded border px-3 py-1.5 text-sm" onClick={() => { setForm(requirementForm(requirement)); setEditing((value) => !value); }}>{editing ? 'Cerrar' : 'Gestionar'}</button> : null}</div></div>
    <div className="grid grid-cols-2 gap-2 border-t bg-gray-50 px-4 py-2 text-xs text-gray-600 md:grid-cols-4"><span>Existencia: {fmt(requirement.stockOnHandSnapshot)}</span><span>Reservado: {fmt(requirement.stockReservedSnapshot)}</span><span>Disponible al generar: {fmt(requirement.stockAvailableSnapshot)}</span><span>Cobertura asignada: {fmt(requirement.stockCoveredQuantity)}</span></div>
    {editing ? <div className="space-y-3 border-t p-4"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Ruta planificada"><select className="w-full rounded border px-3 py-2" value={form.plannedSupplyType} onChange={(e) => setForm({ ...form, plannedSupplyType: e.target.value as SupplyType })}>{Object.entries(supplyTypeLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Estado"><select className="w-full rounded border px-3 py-2" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as ManufacturingSupplyRequirementStatus })}>{Object.entries(supplyRequirementStatusLabel).filter(([value]) => value !== 'CANCELED').map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label={`Cantidad cubierta (${requirement.uomSnapshot})`}><input type="number" min={0} max={requirement.requiredQuantity} step="any" className="w-full rounded border px-3 py-2" value={form.fulfilledQuantity} onChange={(e) => setForm({ ...form, fulfilledQuantity: e.target.value })} /></Field><Field label="Fecha esperada"><input type="date" className="w-full rounded border px-3 py-2" value={form.expectedAt} onChange={(e) => setForm({ ...form, expectedAt: e.target.value })} /></Field><Field label="Proveedor / responsable"><input className="w-full rounded border px-3 py-2" value={form.supplier} onChange={(e) => setForm({ ...form, supplier: e.target.value })} /></Field><Field label="OC / OP / referencia"><input className="w-full rounded border px-3 py-2" value={form.externalReference} onChange={(e) => setForm({ ...form, externalReference: e.target.value })} /></Field><Field label="Notas"><input className="w-full rounded border px-3 py-2" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field>{requirement.isOptionalSnapshot ? <label className="flex items-center gap-2 self-end py-2 text-sm"><input type="checkbox" checked={form.included} onChange={(e) => setForm({ ...form, included: e.target.checked })} /> Incluir opción en el proyecto</label> : null}</div><div className="flex justify-end"><button disabled={busy} className="rounded bg-black px-4 py-2 text-sm text-white" onClick={save}>{busy ? 'Guardando…' : 'Guardar gestión'}</button></div></div> : null}
  </div>;
}

function requirementForm(item: ManufacturingSupplyRequirement) { return { included: item.included, plannedSupplyType: item.plannedSupplyType, status: item.status, fulfilledQuantity: String(item.fulfilledQuantity), supplier: item.supplier || '', externalReference: item.externalReference || '', expectedAt: item.expectedAt ? new Date(item.expectedAt).toISOString().slice(0, 10) : '', notes: item.notes || '' }; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1 text-sm"><span className="text-gray-600">{label}</span>{children}</label>; }
function Metric({ label, value, tone = 'gray' }: { label: string; value: string | number; tone?: 'gray' | 'green' | 'amber' }) { const color = { gray: 'text-gray-900', green: 'text-emerald-700', amber: 'text-amber-700' }[tone]; return <div><div className="text-xs text-gray-500">{label}</div><div className={`text-lg font-semibold ${color}`}>{value}</div></div>; }
function Quantity({ label, value, uom, tone = 'gray' }: { label: string; value: number; uom: string; tone?: 'gray' | 'green' | 'amber' }) { const color = { gray: '', green: 'text-emerald-700', amber: 'text-amber-700' }[tone]; return <div><div className="text-xs text-gray-500">{label}</div><div className={`font-semibold ${color}`}>{fmt(value)} <span className="text-xs font-normal">{uom}</span></div></div>; }
function fmt(value: number) { return new Intl.NumberFormat('es-CO', { maximumFractionDigits: 6 }).format(Number(value || 0)); }
function apiError(error: any, fallback: string) { const message = String(error?.message || ''); try { const start = message.indexOf('{'); if (start >= 0) { const parsed = JSON.parse(message.slice(start)); return Array.isArray(parsed.message) ? parsed.message.join('\n') : parsed.message || fallback; } } catch {} return message || fallback; }
