'use client';

import { useState } from 'react';
import { apiFetch } from '@/lib/api';
import { useApiSWR } from '@/lib/swr';
import { dateLabel, type ManufacturingDispatch, type ManufacturingDispatchDocumentType, type ManufacturingDispatchPackageType, type ManufacturingFatExecution, type ManufacturingOrder, type ManufacturingUser } from '@/lib/manufacturing';

type Auth = { token?: string; tenantSlug?: string };

export function ManufacturingDispatchTab({ order, role, auth, onChanged }: { order: ManufacturingOrder; role: string; auth: Auth; onChanged: () => void | Promise<unknown> }) {
  const { data, error, isLoading, mutate } = useApiSWR<ManufacturingDispatch[]>(`/manufacturing/orders/${order.id}/dispatches`, auth.token, auth.tenantSlug);
  const { data: fats } = useApiSWR<ManufacturingFatExecution[]>(`/manufacturing/orders/${order.id}/fat-executions`, auth.token, auth.tenantSlug);
  const { data: users } = useApiSWR<ManufacturingUser[]>(role === 'ADMIN' ? '/users' : null, auth.token, auth.tenantSlug);
  const [message, setMessage] = useState(''); const dispatches = data || [];
  const eligibleUnits = (order.units || []).filter((unit) => (fats || []).some((fat) => fat.manufacturedUnitId === unit.id && fat.status === 'APPROVED') && !dispatches.some((dispatch) => dispatch.manufacturedUnitId === unit.id));
  async function accept(next: ManufacturingDispatch[]) { setMessage(''); await mutate(next, { revalidate: false }); await onChanged(); }
  return <div className="space-y-4"><div><h2 className="text-lg font-semibold">Despacho y logística de salida</h2><p className="text-sm text-gray-600">Embalaje, bultos, documentos, autorización FAT, transporte y confirmación de entrega por unidad.</p></div>{message ? <div className="whitespace-pre-wrap rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</div> : null}{error ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">No se pudieron cargar los despachos.</div> : null}{role === 'ADMIN' && eligibleUnits.length ? <CreateDispatch units={eligibleUnits} order={order} auth={auth} onChanged={accept} onError={setMessage} /> : null}{isLoading ? <div className="py-8 text-center text-sm text-gray-500">Cargando despachos…</div> : null}{!isLoading && !dispatches.length ? <div className="rounded-lg border border-dashed p-10 text-center"><div className="font-medium">No hay unidades habilitadas para despacho</div><p className="mt-1 text-sm text-gray-600">La unidad debe tener un FAT aprobado.</p></div> : null}<div className="space-y-4">{dispatches.map((dispatch) => <DispatchCard key={dispatch.id} dispatch={dispatch} users={users || []} role={role} auth={auth} onChanged={accept} onError={setMessage} />)}</div></div>;
}

function CreateDispatch({ units, order, auth, onChanged, onError }: { units: NonNullable<ManufacturingOrder['units']>; order: ManufacturingOrder; auth: Auth; onChanged: (items: ManufacturingDispatch[]) => void | Promise<void>; onError: (value: string) => void }) {
  const [destination, setDestination] = useState(order.destination || ''); const [address, setAddress] = useState(''); const [busy, setBusy] = useState('');
  async function create(unitId: string) { if (!auth.token || !auth.tenantSlug) return; setBusy(unitId); onError(''); try { const next = await apiFetch<ManufacturingDispatch[]>(`/manufacturing/units/${unitId}/dispatches`, { method: 'POST', token: auth.token, tenantSlug: auth.tenantSlug, body: { destination, deliveryAddress: address } }); await onChanged(next); } catch (error: any) { onError(apiError(error, 'No se pudo crear el despacho')); } finally { setBusy(''); } }
  return <div className="rounded-lg border border-cyan-200 bg-cyan-50 p-4"><strong>Unidades con FAT aprobado</strong><div className="mt-3 grid gap-2 md:grid-cols-2"><input className="rounded border bg-white px-3 py-2 text-sm" placeholder="Destino" value={destination} onChange={(event) => setDestination(event.target.value)} /><input className="rounded border bg-white px-3 py-2 text-sm" placeholder="Dirección de entrega" value={address} onChange={(event) => setAddress(event.target.value)} /></div><div className="mt-3 flex flex-wrap gap-2">{units.map((unit) => <button key={unit.id} disabled={!!busy} className="rounded bg-cyan-800 px-3 py-2 text-sm text-white disabled:opacity-50" onClick={() => create(unit.id)}>{busy === unit.id ? 'Creando…' : `Preparar despacho · Unidad ${unit.unitNumber}`}</button>)}</div></div>;
}

function DispatchCard({ dispatch, users, role, auth, onChanged, onError }: { dispatch: ManufacturingDispatch; users: ManufacturingUser[]; role: string; auth: Auth; onChanged: (items: ManufacturingDispatch[]) => void | Promise<void>; onError: (value: string) => void }) {
  const [open, setOpen] = useState(!['DELIVERED', 'CANCELED'].includes(dispatch.status)); const [busy, setBusy] = useState('');
  async function call(path: string, body: any, method = 'POST', action = path) { if (!auth.token || !auth.tenantSlug) return; setBusy(action); onError(''); try { const next = await apiFetch<ManufacturingDispatch[]>(`/manufacturing/${path}`, { method, token: auth.token, tenantSlug: auth.tenantSlug, body }); await onChanged(next); } catch (error: any) { onError(apiError(error, 'No se pudo actualizar el despacho')); } finally { setBusy(''); } }
  async function execute() { const trackingNumber = window.prompt('Guía o número de seguimiento:'); if (!trackingNumber) return; const driverName = window.prompt('Conductor (opcional):'); const vehiclePlate = window.prompt('Placa del vehículo (opcional):'); await call(`dispatches/${dispatch.id}/dispatch`, { lockVersion: dispatch.lockVersion, trackingNumber, driverName, vehiclePlate }, 'POST', 'dispatch'); }
  async function deliver() { const receivedByName = window.prompt('Nombre de quien recibe:'); if (!receivedByName) return; const proofReference = window.prompt('Referencia del soporte de entrega:'); if (!proofReference) return; await call(`dispatches/${dispatch.id}/deliver`, { lockVersion: dispatch.lockVersion, receivedByName, proofReference }, 'POST', 'deliver'); }
  async function cancel() { const reason = window.prompt('Motivo de cancelación:'); if (!reason) return; await call(`dispatches/${dispatch.id}/cancel`, { lockVersion: dispatch.lockVersion, reason }, 'POST', 'cancel'); }
  return <div className={`rounded-lg border ${dispatch.status === 'DELIVERED' ? 'border-emerald-300' : dispatch.status === 'CANCELED' ? 'border-red-200' : ''}`}><button className="flex w-full flex-wrap items-center justify-between gap-3 p-4 text-left" onClick={() => setOpen((value) => !value)}><div><div className="flex items-center gap-2"><strong>{dispatch.dispatchCode}</strong><span className={`rounded-full px-2 py-0.5 text-xs ${statusClass(dispatch.status)}`}>{statusLabel(dispatch.status)}</span>{dispatch.summary.fatGateOpen ? <span className="rounded bg-emerald-100 px-2 py-0.5 text-xs text-emerald-800">FAT aprobado</span> : null}</div><div className="text-xs text-gray-500">Unidad {dispatch.manufacturedUnit.unitNumber} · Serial {dispatch.serialNumberSnapshot || dispatch.manufacturedUnit.serialNumber || 'pendiente'} · Responsable {dispatch.responsibleName}</div></div><div className="text-right"><strong>{dispatch.summary.progressPercent}% embalaje</strong><div className="text-xs text-gray-500">{dispatch.summary.packageCount} bulto(s) · {formatNumber(dispatch.summary.grossWeightKg)} kg · {dispatch.summary.documentCount} documento(s)</div></div></button>{open ? <div className="space-y-4 border-t p-4">{['DRAFT', 'PREPARING'].includes(dispatch.status) && role === 'ADMIN' ? <LogisticsForm dispatch={dispatch} users={users} busy={busy} call={call} /> : <LogisticsSummary dispatch={dispatch} />}
    <div className="flex flex-wrap gap-2">{dispatch.status === 'DRAFT' ? <button disabled={!!busy} className="rounded bg-black px-3 py-2 text-sm text-white" onClick={() => call(`dispatches/${dispatch.id}/start`, { lockVersion: dispatch.lockVersion }, 'POST', 'start')}>Iniciar preparación</button> : null}{dispatch.status === 'PREPARING' ? <button disabled={!!busy} className="rounded bg-cyan-800 px-3 py-2 text-sm text-white" onClick={() => call(`dispatches/${dispatch.id}/ready`, { lockVersion: dispatch.lockVersion }, 'POST', 'ready')}>Cerrar embalaje</button> : null}{dispatch.status === 'READY' && role === 'ADMIN' ? <button disabled={!!busy} className="rounded bg-emerald-700 px-3 py-2 text-sm text-white" onClick={() => call(`dispatches/${dispatch.id}/authorize`, { lockVersion: dispatch.lockVersion }, 'POST', 'authorize')}>Autorizar salida</button> : null}{dispatch.status === 'AUTHORIZED' ? <button disabled={!!busy} className="rounded bg-indigo-800 px-3 py-2 text-sm text-white" onClick={execute}>Confirmar salida</button> : null}{dispatch.status === 'DISPATCHED' ? <button disabled={!!busy} className="rounded bg-emerald-700 px-3 py-2 text-sm text-white" onClick={deliver}>Confirmar entrega</button> : null}{role === 'ADMIN' && ['DRAFT', 'PREPARING', 'READY', 'AUTHORIZED'].includes(dispatch.status) ? <button disabled={!!busy} className="rounded border border-red-300 px-3 py-2 text-sm text-red-700" onClick={cancel}>Cancelar</button> : null}{role === 'ADMIN' && dispatch.status === 'CANCELED' ? <button disabled={!!busy} className="rounded border px-3 py-2 text-sm" onClick={() => call(`dispatches/${dispatch.id}/reopen`, { lockVersion: dispatch.lockVersion }, 'POST', 'reopen')}>Reabrir expediente</button> : null}</div>
    {dispatch.status === 'PREPARING' ? <Checklist dispatch={dispatch} busy={busy} call={call} /> : <ChecklistSummary dispatch={dispatch} />}
    {dispatch.status === 'PREPARING' ? <PackageForm dispatch={dispatch} busy={busy} call={call} /> : null}<PackageList dispatch={dispatch} busy={busy} call={call} />
    {['PREPARING', 'READY', 'AUTHORIZED'].includes(dispatch.status) ? <DocumentForm dispatch={dispatch} busy={busy} call={call} /> : null}<DocumentList dispatch={dispatch} busy={busy} call={call} />
    {dispatch.authorizedAt ? <div className="rounded bg-emerald-50 p-3 text-xs">Salida autorizada por {dispatch.authorizedByName} ({dispatch.authorizedByRole}) · {dateLabel(dispatch.authorizedAt, true)}</div> : null}{dispatch.dispatchedAt ? <div className="rounded bg-indigo-50 p-3 text-xs">Despachado por {dispatch.dispatchedByName} · {dateLabel(dispatch.dispatchedAt, true)} · Guía {dispatch.trackingNumber}</div> : null}{dispatch.deliveredAt ? <div className="rounded bg-emerald-50 p-3 text-xs">Entregado a {dispatch.receivedByName} · {dateLabel(dispatch.deliveredAt, true)} · Soporte {dispatch.deliveryProofReference}</div> : null}{dispatch.canceledReason ? <div className="rounded bg-red-50 p-3 text-xs text-red-700">Cancelado: {dispatch.canceledReason}</div> : null}
  </div> : null}</div>;
}

function LogisticsForm({ dispatch, users, busy, call }: { dispatch: ManufacturingDispatch; users: ManufacturingUser[]; busy: string; call: Function }) {
  const [destination, setDestination] = useState(dispatch.destination || ''); const [address, setAddress] = useState(dispatch.deliveryAddress || ''); const [contactName, setContactName] = useState(dispatch.contactName || ''); const [contactPhone, setContactPhone] = useState(dispatch.contactPhone || ''); const [carrierName, setCarrierName] = useState(dispatch.carrierName || ''); const [responsibleUserId, setResponsibleUserId] = useState(dispatch.responsibleUserId); const [plannedDispatchAt, setPlannedDispatchAt] = useState(dispatch.plannedDispatchAt?.slice(0, 16) || '');
  return <div className="rounded bg-gray-50 p-3"><div className="mb-2 text-sm font-medium">Datos logísticos</div><div className="grid gap-2 md:grid-cols-3"><input className="rounded border px-2 py-1.5 text-sm" placeholder="Destino" value={destination} onChange={(event) => setDestination(event.target.value)} /><input className="rounded border px-2 py-1.5 text-sm md:col-span-2" placeholder="Dirección de entrega" value={address} onChange={(event) => setAddress(event.target.value)} /><input className="rounded border px-2 py-1.5 text-sm" placeholder="Contacto" value={contactName} onChange={(event) => setContactName(event.target.value)} /><input className="rounded border px-2 py-1.5 text-sm" placeholder="Teléfono" value={contactPhone} onChange={(event) => setContactPhone(event.target.value)} /><input className="rounded border px-2 py-1.5 text-sm" placeholder="Transportista" value={carrierName} onChange={(event) => setCarrierName(event.target.value)} /><select className="rounded border px-2 py-1.5 text-sm" value={responsibleUserId} onChange={(event) => setResponsibleUserId(event.target.value)}>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><input className="rounded border px-2 py-1.5 text-sm" type="datetime-local" value={plannedDispatchAt} onChange={(event) => setPlannedDispatchAt(event.target.value)} /><button disabled={!!busy} className="rounded border bg-white px-3 py-1.5 text-sm" onClick={() => call(`dispatches/${dispatch.id}`, { lockVersion: dispatch.lockVersion, destination, deliveryAddress: address, contactName, contactPhone, carrierName, responsibleUserId, plannedDispatchAt: plannedDispatchAt || null }, 'PATCH', 'logistics')}>Guardar logística</button></div></div>;
}

function LogisticsSummary({ dispatch }: { dispatch: ManufacturingDispatch }) { return <div className="grid gap-2 rounded bg-gray-50 p-3 text-xs md:grid-cols-3"><div><span className="text-gray-500">Destino</span><br />{dispatch.destination || '—'}<br />{dispatch.deliveryAddress || '—'}</div><div><span className="text-gray-500">Transportista</span><br />{dispatch.carrierName || '—'}{dispatch.vehiclePlate ? ` · ${dispatch.vehiclePlate}` : ''}</div><div><span className="text-gray-500">Fecha planeada</span><br />{dateLabel(dispatch.plannedDispatchAt, true)}</div></div>; }

function Checklist({ dispatch, busy, call }: { dispatch: ManufacturingDispatch; busy: string; call: Function }) { async function complete(item: ManufacturingDispatch['checklistItems'][number]) { const evidenceReference = item.evidenceRequired ? window.prompt('Referencia de evidencia:') : window.prompt('Referencia de evidencia (opcional):'); if (item.evidenceRequired && !evidenceReference) return; const notes = window.prompt('Notas (opcional):'); await call(`dispatch-checklist/${item.id}`, { lockVersion: item.lockVersion, status: 'COMPLETED', evidenceReference, notes }, 'PATCH', `check-${item.id}`); } return <div><div className="mb-2 text-sm font-medium">Checklist de embalaje</div><div className="space-y-1">{dispatch.checklistItems.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-2 text-sm"><div><strong>{item.position}. {item.name}</strong><div className="text-xs text-gray-500">{item.description}{item.evidenceRequired ? ' · Evidencia obligatoria' : ''}</div></div>{item.status === 'PENDING' ? <button disabled={!!busy} className="rounded border px-2 py-1 text-xs" onClick={() => complete(item)}>Completar</button> : <div className="flex items-center gap-2"><span className="text-xs text-emerald-700">Completado por {item.completedByName}</span><button disabled={!!busy} className="text-xs underline" onClick={() => call(`dispatch-checklist/${item.id}`, { lockVersion: item.lockVersion, status: 'PENDING' }, 'PATCH', `check-${item.id}`)}>Reabrir</button></div>}</div>)}</div></div>; }
function ChecklistSummary({ dispatch }: { dispatch: ManufacturingDispatch }) { return <div><div className="mb-2 text-sm font-medium">Checklist ({dispatch.summary.checklistCompletedCount}/{dispatch.summary.checklistCount})</div><div className="grid gap-1 md:grid-cols-2">{dispatch.checklistItems.map((item) => <div key={item.id} className="rounded border p-2 text-xs">{item.status === 'COMPLETED' ? '✓' : item.status === 'NOT_APPLICABLE' ? '—' : '○'} {item.name}{item.evidenceReference ? ` · ${item.evidenceReference}` : ''}</div>)}</div></div>; }

function PackageForm({ dispatch, busy, call }: { dispatch: ManufacturingDispatch; busy: string; call: Function }) { const [packageType, setPackageType] = useState<ManufacturingDispatchPackageType>('CRATE'); const [description, setDescription] = useState('Máquina embalada'); const [grossWeightKg, setGrossWeightKg] = useState(''); const [dimensions, setDimensions] = useState({ lengthCm: '', widthCm: '', heightCm: '' }); const [sealNumber, setSealNumber] = useState(''); async function add() { await call(`dispatches/${dispatch.id}/packages`, { packageType, description, grossWeightKg: Number(grossWeightKg), ...dimensions, sealNumber: sealNumber || null }, 'POST', 'package'); setGrossWeightKg(''); setSealNumber(''); } return <div className="rounded bg-amber-50 p-3"><div className="mb-2 text-sm font-medium">Agregar bulto</div><div className="flex flex-wrap items-end gap-2"><select className="rounded border px-2 py-1.5 text-sm" value={packageType} onChange={(event) => setPackageType(event.target.value as ManufacturingDispatchPackageType)}><option value="CRATE">Guacal</option><option value="PALLET">Estiba</option><option value="BOX">Caja</option><option value="LOOSE">Carga suelta</option><option value="OTHER">Otro</option></select><input className="rounded border px-2 py-1.5 text-sm" placeholder="Descripción" value={description} onChange={(event) => setDescription(event.target.value)} /><input className="w-24 rounded border px-2 py-1.5 text-sm" type="number" placeholder="Peso kg" value={grossWeightKg} onChange={(event) => setGrossWeightKg(event.target.value)} />{(['lengthCm', 'widthCm', 'heightCm'] as const).map((key) => <input key={key} className="w-20 rounded border px-2 py-1.5 text-sm" type="number" placeholder={key === 'lengthCm' ? 'L cm' : key === 'widthCm' ? 'A cm' : 'H cm'} value={dimensions[key]} onChange={(event) => setDimensions((value) => ({ ...value, [key]: event.target.value }))} />)}<input className="w-28 rounded border px-2 py-1.5 text-sm" placeholder="Sello" value={sealNumber} onChange={(event) => setSealNumber(event.target.value)} /><button disabled={!!busy || Number(grossWeightKg) <= 0} className="rounded border bg-white px-3 py-1.5 text-sm" onClick={add}>Registrar bulto</button></div></div>; }
function PackageList({ dispatch, busy, call }: { dispatch: ManufacturingDispatch; busy: string; call: Function }) { return <div><div className="mb-2 text-sm font-medium">Bultos</div>{dispatch.packages.length ? <div className="grid gap-2 md:grid-cols-2">{dispatch.packages.map((item) => <div key={item.id} className="rounded border p-2 text-xs"><strong>{item.packageCode}</strong> · {packageTypeLabel(item.packageType)} · {item.description}<br />{formatNumber(item.grossWeightKg)} kg{item.lengthCm ? ` · ${item.lengthCm}×${item.widthCm}×${item.heightCm} cm` : ''}{item.sealNumber ? ` · Sello ${item.sealNumber}` : ''}{dispatch.status === 'PREPARING' ? <button disabled={!!busy} className="ml-2 text-red-700 underline" onClick={() => call(`dispatch-packages/${item.id}`, {}, 'DELETE', `package-${item.id}`)}>Retirar</button> : null}</div>)}</div> : <div className="text-xs text-gray-400">Sin bultos registrados</div>}</div>; }

function DocumentForm({ dispatch, busy, call }: { dispatch: ManufacturingDispatch; busy: string; call: Function }) { const [documentType, setDocumentType] = useState<ManufacturingDispatchDocumentType>('PACKING_LIST'); const [title, setTitle] = useState('Lista de empaque'); const [reference, setReference] = useState(''); async function add() { await call(`dispatches/${dispatch.id}/documents`, { documentType, title, reference }, 'POST', 'document'); setReference(''); } return <div className="rounded bg-sky-50 p-3"><div className="mb-2 text-sm font-medium">Agregar documento</div><div className="flex flex-wrap gap-2"><select className="rounded border px-2 py-1.5 text-sm" value={documentType} onChange={(event) => setDocumentType(event.target.value as ManufacturingDispatchDocumentType)}>{Object.entries(documentTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input className="rounded border px-2 py-1.5 text-sm" placeholder="Título" value={title} onChange={(event) => setTitle(event.target.value)} /><input className="min-w-64 flex-1 rounded border px-2 py-1.5 text-sm" placeholder="Referencia o documento" value={reference} onChange={(event) => setReference(event.target.value)} /><button disabled={!!busy || !title || !reference} className="rounded border bg-white px-3 py-1.5 text-sm" onClick={add}>Registrar documento</button></div></div>; }
function DocumentList({ dispatch, busy, call }: { dispatch: ManufacturingDispatch; busy: string; call: Function }) { return <div><div className="mb-2 text-sm font-medium">Documentos</div>{dispatch.documents.length ? dispatch.documents.map((item) => <div key={item.id} className="border-t py-1 text-xs text-gray-600">{documentTypeLabels[item.documentType]} · {item.title}{item.reference ? ` · ${item.reference}` : ''} · {item.createdByName}{['PREPARING', 'READY', 'AUTHORIZED'].includes(dispatch.status) ? <button disabled={!!busy} className="ml-2 text-red-700 underline" onClick={() => call(`dispatch-documents/${item.id}`, {}, 'DELETE', `document-${item.id}`)}>Retirar</button> : null}</div>) : <div className="text-xs text-gray-400">Sin documentos</div>}</div>; }

const documentTypeLabels: Record<ManufacturingDispatchDocumentType, string> = { PACKING_LIST: 'Lista de empaque', TRANSPORT_DOCUMENT: 'Documento de transporte', COMMERCIAL_INVOICE: 'Factura comercial', INSURANCE: 'Seguro', CERTIFICATE: 'Certificado', MANUAL: 'Manual', FAT_REPORT: 'Informe FAT', OTHER: 'Otro' };
function statusLabel(status: ManufacturingDispatch['status']) { return { DRAFT: 'Borrador', PREPARING: 'En preparación', READY: 'Embalaje listo', AUTHORIZED: 'Salida autorizada', DISPATCHED: 'En tránsito', DELIVERED: 'Entregado', CANCELED: 'Cancelado' }[status]; }
function statusClass(status: ManufacturingDispatch['status']) { return status === 'DELIVERED' ? 'bg-emerald-100 text-emerald-800' : status === 'DISPATCHED' ? 'bg-indigo-100 text-indigo-800' : status === 'AUTHORIZED' ? 'bg-cyan-100 text-cyan-800' : status === 'READY' ? 'bg-amber-100 text-amber-800' : status === 'CANCELED' ? 'bg-red-100 text-red-800' : 'bg-gray-100 text-gray-700'; }
function packageTypeLabel(type: ManufacturingDispatchPackageType) { return { CRATE: 'Guacal', PALLET: 'Estiba', BOX: 'Caja', LOOSE: 'Carga suelta', OTHER: 'Otro' }[type]; }
function formatNumber(value: number) { return new Intl.NumberFormat('es-CO', { maximumFractionDigits: 3 }).format(Number(value || 0)); }
function apiError(error: any, fallback: string) { const message = String(error?.message || ''); try { const start = message.indexOf('{'); if (start >= 0) { const parsed = JSON.parse(message.slice(start)); return Array.isArray(parsed.message) ? parsed.message.join('\n') : parsed.message || fallback; } } catch {} return message || fallback; }
