'use client';

import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { useApiSWR } from '@/lib/swr';
import { dateLabel, supplyTypeLabel, type ManufacturingKit, type ManufacturingKitLine, type ManufacturingOrder } from '@/lib/manufacturing';

type Auth = { token?: string; tenantSlug?: string };

export function ManufacturingKitsTab({ order, role, auth, onChanged }: { order: ManufacturingOrder; role: string; auth: Auth; onChanged: () => void | Promise<unknown> }) {
  const { data, error, isLoading, mutate } = useApiSWR<ManufacturingKit[]>(`/manufacturing/orders/${order.id}/kits`, auth.token, auth.tenantSlug);
  const kits = data || []; const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const canManage = role === 'ADMIN' && !['ON_HOLD', 'CANCELED'].includes(order.status);
  async function generate() { if (!auth.token || !auth.tenantSlug) return; setBusy(true); setMessage(''); try { const next = await apiFetch<ManufacturingKit[]>(`/manufacturing/orders/${order.id}/kits/generate`, { method: 'POST', token: auth.token, tenantSlug: auth.tenantSlug, body: {} }); await mutate(next, { revalidate: false }); await onChanged(); } catch (error: any) { setMessage(apiError(error, 'No se pudieron generar los kits')); } finally { setBusy(false); } }
  async function accept(next: ManufacturingKit[]) { setMessage(''); await mutate(next, { revalidate: false }); await onChanged(); }
  const released = kits.filter((kit) => kit.status === 'RELEASED').length; const ready = kits.filter((kit) => kit.status === 'READY').length; const shortages = kits.reduce((sum, kit) => sum + kit.summary.shortageCount, 0);
  return <div className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Preparación y liberación a ensamble</h2><p className="text-sm text-gray-600">Un kit por unidad, abastecido únicamente con cantidades entregadas o aprobadas.</p></div>{canManage ? <button disabled={busy} className="rounded bg-black px-4 py-2 text-sm text-white" onClick={generate}>{busy ? 'Generando…' : kits.length ? 'Completar kits faltantes' : 'Generar kits por unidad'}</button> : null}</div>{message ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700 whitespace-pre-wrap">{message}</div> : null}{error ? <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">No se pudieron cargar los kits.</div> : null}{isLoading ? <div className="py-8 text-center text-sm text-gray-500">Cargando kits…</div> : null}{kits.length ? <div className="grid grid-cols-3 gap-3"><Metric label="Kits" value={kits.length} /><Metric label="Listos / liberados" value={`${ready} / ${released}`} tone="green" /><Metric label="Líneas con faltante" value={shortages} tone={shortages ? 'amber' : 'green'} /></div> : null}{!isLoading && !kits.length ? <div className="rounded-lg border border-dashed p-10 text-center"><div className="font-medium">No hay kits preparados</div><p className="mt-1 text-sm text-gray-600">Se requiere un plan de abastecimiento vigente y unidades planificadas.</p></div> : null}<div className="space-y-3">{kits.map((kit) => <KitCard key={kit.id} kit={kit} auth={auth} editable={canManage} onChanged={accept} onError={setMessage} />)}</div></div>;
}

function KitCard({ kit, auth, editable, onChanged, onError }: { kit: ManufacturingKit; auth: Auth; editable: boolean; onChanged: (kits: ManufacturingKit[]) => void | Promise<void>; onError: (value: string) => void }) {
  const [open, setOpen] = useState(kit.status !== 'RELEASED'); const [busy, setBusy] = useState('');
  const mutable = editable && !['RELEASED', 'CANCELED'].includes(kit.status);
  async function act(action: 'release' | 'cancel') { if (!auth.token || !auth.tenantSlug) return; const text = window.prompt(action === 'release' ? 'Notas de liberación (opcional):' : 'Motivo de cancelación:'); if (action === 'cancel' && !text?.trim()) return; setBusy(action); onError(''); try { const next = await apiFetch<ManufacturingKit[]>(`/manufacturing/kits/${kit.id}/${action}`, { method: 'POST', token: auth.token, tenantSlug: auth.tenantSlug, body: action === 'release' ? { lockVersion: kit.lockVersion, notes: text || null } : { lockVersion: kit.lockVersion, reason: text } }); await onChanged(next); } catch (error: any) { onError(apiError(error, `No se pudo ${action === 'release' ? 'liberar' : 'cancelar'} el kit`)); } finally { setBusy(''); } }
  return <div className={`rounded-lg border ${kit.status === 'CANCELED' ? 'bg-gray-50 opacity-75' : 'bg-white'}`}><button className="flex w-full flex-wrap items-center justify-between gap-3 p-4 text-left" onClick={() => setOpen((value) => !value)}><div><div className="flex items-center gap-2"><strong>{kit.kitCode}</strong><span className={`rounded-full px-2 py-0.5 text-xs ${kitStatusClass(kit.status)}`}>{kitStatusLabel(kit.status)}</span></div><div className="text-xs text-gray-500">Unidad {kit.manufacturedUnit.unitNumber}{kit.manufacturedUnit.serialNumber ? ` · S/N ${kit.manufacturedUnit.serialNumber}` : ''} · Liberación {kit.releaseCodeSnapshot}</div></div><div className="text-right text-sm"><div>{kit.summary.completeCount}/{kit.summary.lineCount} líneas completas</div><div className="text-xs text-gray-500">{kit.summary.shortageCount} faltantes · {open ? '▲' : '▼'}</div></div></button>{open ? <div className="space-y-3 border-t p-4"><div className="space-y-2">{kit.lines.map((line) => <KitLineRow key={line.id} line={line} auth={auth} editable={mutable} onChanged={onChanged} onError={onError} />)}</div><div className="flex flex-wrap justify-between gap-2 border-t pt-3"><div className="text-xs text-gray-500">{kit.releasedAt ? `Liberado por ${kit.releasedByName} · ${dateLabel(kit.releasedAt, true)}` : kit.canceledReason ? `Cancelado: ${kit.canceledReason}` : 'La liberación exige todas las líneas completas o con excepción autorizada.'}</div>{editable && kit.status !== 'CANCELED' ? <div className="flex gap-2">{kit.status !== 'RELEASED' ? <button disabled={!!busy} className="rounded border border-red-200 px-3 py-1.5 text-sm text-red-700" onClick={() => act('cancel')}>{busy === 'cancel' ? 'Cancelando…' : 'Cancelar kit'}</button> : null}{kit.status === 'READY' ? <button disabled={!!busy} className="rounded bg-emerald-700 px-4 py-1.5 text-sm text-white" onClick={() => act('release')}>{busy === 'release' ? 'Liberando…' : 'Liberar a ensamble'}</button> : null}</div> : null}</div></div> : null}</div>;
}

function KitLineRow({ line, auth, editable, onChanged, onError }: { line: ManufacturingKitLine; auth: Auth; editable: boolean; onChanged: (kits: ManufacturingKit[]) => void | Promise<void>; onError: (value: string) => void }) {
  const [quantity, setQuantity] = useState(String(Math.min(line.shortageQuantity, line.availableToAllocate))); const [waived, setWaived] = useState(String(line.waivedQuantity)); const [reason, setReason] = useState(line.waiverReason || ''); const [busy, setBusy] = useState('');
  useEffect(() => { setQuantity(String(Math.min(line.shortageQuantity, line.availableToAllocate))); setWaived(String(line.waivedQuantity)); setReason(line.waiverReason || ''); }, [line.lockVersion, line.shortageQuantity, line.availableToAllocate, line.waivedQuantity, line.waiverReason]);
  async function call(action: 'allocate' | 'unallocate' | 'waive', body: any) { if (!auth.token || !auth.tenantSlug) return; setBusy(action); onError(''); try { const next = await apiFetch<ManufacturingKit[]>(`/manufacturing/kit-lines/${line.id}/${action}`, { method: 'POST', token: auth.token, tenantSlug: auth.tenantSlug, body: { lockVersion: line.lockVersion, ...body } }); await onChanged(next); } catch (error: any) { onError(apiError(error, 'No se pudo actualizar la línea del kit')); } finally { setBusy(''); } }
  return <div className={`rounded border p-3 ${line.shortageQuantity > 0 ? 'border-amber-200 bg-amber-50/40' : 'border-emerald-200 bg-emerald-50/30'}`}><div className="grid gap-2 md:grid-cols-[70px_1fr_100px_100px_110px]"><div><div className="text-xs text-gray-500">Pos.</div><strong>{line.positionSnapshot}</strong></div><div><strong>{line.itemCodeSnapshot}</strong><div className="text-sm text-gray-700">{line.descriptionSnapshot}</div><div className="text-xs text-gray-500">{supplyTypeLabel[line.supplyRequirement.plannedSupplyType]} · Aprobado global {fmt(line.supplyRequirement.fulfilledQuantity)} · disponible sin asignar {fmt(line.availableToAllocate)}</div></div><Quantity label="Requerido" value={line.requiredQuantity} uom={line.uomSnapshot} /><Quantity label="Asignado" value={line.allocatedQuantity} uom={line.uomSnapshot} tone="green" /><Quantity label="Faltante" value={line.shortageQuantity} uom={line.uomSnapshot} tone={line.shortageQuantity ? 'amber' : 'green'} /></div>{line.waivedQuantity > 0 ? <div className="mt-2 rounded bg-amber-100 px-2 py-1 text-xs text-amber-900">Excepción {fmt(line.waivedQuantity)} {line.uomSnapshot}: {line.waiverReason} · {line.waivedByName}</div> : null}{editable ? <div className="mt-2 flex flex-wrap items-end gap-2 border-t pt-2"><label className="text-xs">Cantidad<div><input type="number" min={0} step="any" className="mt-1 w-24 rounded border bg-white px-2 py-1.5" value={quantity} onChange={(e) => setQuantity(e.target.value)} /></div></label><button disabled={!!busy || Number(quantity) <= 0 || line.availableToAllocate <= 0} className="rounded bg-sky-700 px-3 py-1.5 text-xs text-white disabled:opacity-50" onClick={() => call('allocate', { quantity: Number(quantity) })}>{busy === 'allocate' ? 'Asignando…' : 'Asignar'}</button><button disabled={!!busy || Number(quantity) <= 0 || line.allocatedQuantity <= 0} className="rounded border bg-white px-3 py-1.5 text-xs disabled:opacity-50" onClick={() => call('unallocate', { quantity: Number(quantity) })}>{busy === 'unallocate' ? 'Retirando…' : 'Retirar'}</button><label className="text-xs">Excepción<div><input type="number" min={0} max={line.requiredQuantity - line.allocatedQuantity} step="any" className="mt-1 w-24 rounded border bg-white px-2 py-1.5" value={waived} onChange={(e) => setWaived(e.target.value)} /></div></label><label className="min-w-48 flex-1 text-xs">Motivo<div><input className="mt-1 w-full rounded border bg-white px-2 py-1.5" value={reason} onChange={(e) => setReason(e.target.value)} /></div></label><button disabled={!!busy} className="rounded border bg-white px-3 py-1.5 text-xs" onClick={() => call('waive', { waivedQuantity: Number(waived), reason })}>{busy === 'waive' ? 'Guardando…' : 'Guardar excepción'}</button></div> : null}</div>;
}

function Metric({ label, value, tone = 'gray' }: { label: string; value: string | number; tone?: 'gray' | 'green' | 'amber' }) { return <div className="rounded border p-3"><div className="text-xs text-gray-500">{label}</div><div className={`text-xl font-semibold ${tone === 'green' ? 'text-emerald-700' : tone === 'amber' ? 'text-amber-700' : ''}`}>{value}</div></div>; }
function Quantity({ label, value, uom, tone = 'gray' }: { label: string; value: number; uom: string; tone?: 'gray' | 'green' | 'amber' }) { return <div><div className="text-xs text-gray-500">{label}</div><div className={`font-semibold ${tone === 'green' ? 'text-emerald-700' : tone === 'amber' ? 'text-amber-700' : ''}`}>{fmt(value)} <span className="text-xs font-normal">{uom}</span></div></div>; }
function kitStatusLabel(status: ManufacturingKit['status']) { return { DRAFT: 'Borrador', PREPARING: 'En preparación', READY: 'Listo', RELEASED: 'Liberado', CANCELED: 'Cancelado' }[status]; }
function kitStatusClass(status: ManufacturingKit['status']) { return { DRAFT: 'bg-gray-100 text-gray-700', PREPARING: 'bg-amber-100 text-amber-800', READY: 'bg-sky-100 text-sky-800', RELEASED: 'bg-emerald-100 text-emerald-800', CANCELED: 'bg-red-100 text-red-800' }[status]; }
function fmt(value: number) { return new Intl.NumberFormat('es-CO', { maximumFractionDigits: 6 }).format(Number(value || 0)); }
function apiError(error: any, fallback: string) { const message = String(error?.message || ''); try { const start = message.indexOf('{'); if (start >= 0) { const parsed = JSON.parse(message.slice(start)); return Array.isArray(parsed.message) ? parsed.message.join('\n') : parsed.message || fallback; } } catch {} return message || fallback; }
