import assert from 'node:assert/strict';
import { randomUUID } from 'crypto';
import { writeFile, unlink } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { AttachmentsService } from '../src/modules/attachments/attachments.service';
import { PrismaService } from '../src/prisma.service';
import { EngineeringService } from '../src/modules/engineering/engineering.service';
import { tenantStorage } from '../src/common/tenant-context';

async function main() {
  const prisma = new PrismaService();
  const db = prisma as any;
  const service = new EngineeringService(prisma);
  const suffix = randomUUID();
  const tenantId = 'engineering-test-' + suffix;
  const otherTenantId = tenantId + '-other';
  const filePath = join(tmpdir(), 'engineering-test-' + suffix + '.txt');
  const act = <T>(userId: string, fn: () => Promise<T>, tenant = tenantId) => tenantStorage.run({ tenantId: tenant, userId }, fn);
  let checks = 0;
  try {
    await prisma.tenant.createMany({ data: [{ id: tenantId, slug: tenantId, name: 'Engineering test' }, { id: otherTenantId, slug: otherTenantId, name: 'Other test' }] });
    const users = await Promise.all(['ADMIN','TECH','TECH','VIEWER'].map((role, i) => prisma.user.create({ data: { tenantId, name: 'Test ' + i, email: i + '@engineering.test', password: 'not-a-login-hash', role: role as any } })));
    const [admin, engineer, reviewer, viewer] = users;
    const otherUser = await prisma.user.create({ data: { tenantId: otherTenantId, name: 'Other', email: 'other@engineering.test', password: 'not-a-login-hash', role: 'ADMIN' } });
    const asset = await prisma.asset.create({ data: { tenantId, code: 'ENG-TEST', name: 'Equipo de prueba', serialNumber: suffix } });
    const otherAsset = await prisma.asset.create({ data: { tenantId: otherTenantId, code: 'ENG-TEST', name: 'Otro equipo' } });
    const origin = await prisma.workOrder.create({ data: { tenantId, assetCode: asset.code, title: 'Hallazgo', kind: 'SERVICE_ORDER', status: 'OPEN' } });
    const dto = { assetId: asset.id, title: 'Mejorar descarga', problem: 'Atascos', expectedBenefit: 'Menos paradas', requestType: 'IMPROVEMENT', discipline: 'MECHANICAL', priority: 'HIGH', originWorkOrderId: origin.id };
    await assert.rejects(act(viewer.id, () => service.create(dto))); checks++;
    await assert.rejects(act(admin.id, () => service.create({ ...dto, assetId: otherAsset.id }))); checks++;
    let row: any = await act(engineer.id, () => service.create(dto));
    assert.equal(row.status, 'DRAFT');
    await assert.rejects(act(otherUser.id, () => service.detail(row.id), otherTenantId)); checks++;
    const apply = async (userId: string, action: string, extra: any = {}) => {
      row = await act(userId, () => service.action(row.id, { version: row.version, action, ...extra }));
    };
    const firstVersion = row.version;
    await apply(engineer.id, 'submit');
    await assert.rejects(act(engineer.id, () => service.action(row.id, { version: firstVersion, action: 'submit' }))); checks++;
    await apply(admin.id, 'request-info', { note: 'Confirmar beneficio' });
    await assert.rejects(act(engineer.id, () => service.action(row.id, { version: row.version, action: 'submit' }))); checks++;
    await apply(engineer.id, 'submit', { note: 'Reducir paradas a una por turno' });
    await apply(admin.id, 'authorize-study', { responsibleUserId: engineer.id, reviewerUserId: reviewer.id, validatorUserId: reviewer.id });
    const proposal = { solution: 'Nueva guía', scope: 'Descarga', materials: 'Acero', estimatedCost: 100, currency: 'COP', downtimeHours: 2, acceptanceCriteria: 'Dos horas sin atascos', documentImpact: 'Actualizar plano y manual' };
    row = await act(engineer.id, () => service.proposal(row.id, row.version, proposal));
    await writeFile(filePath, 'Engineering evidence');
    row = await act(engineer.id, () => service.upload(row.id, row.version, { path: filePath, originalname: 'evidence.txt', mimetype: 'text/plain', size: 20 } as any));
    assert.equal(row.attachments.length, 1);
    await assert.rejects(act(admin.id, () => new AttachmentsService(prisma).remove(row.attachments[0].id))); checks++;
    await apply(engineer.id, 'submit-review');
    await assert.rejects(act(engineer.id, () => service.action(row.id, { version: row.version, action: 'approve' }))); checks++;
    await apply(reviewer.id, 'revise', { note: 'Reducir parada' });
    row = await act(engineer.id, () => service.proposal(row.id, row.version, { ...proposal, downtimeHours: 1 }));
    await apply(engineer.id, 'submit-review');
    await apply(reviewer.id, 'approve');
    assert.equal(row.approvedRevision, 2);
    assert.equal(row.revisions.find((r: any) => r.revision === 1).snapshot.proposal.downtimeHours, 2); checks++;
    assert.equal(row.revisions.find((r: any) => r.revision === 1).snapshot.attachments[0].filename, 'evidence.txt'); checks++;
    await assert.rejects(act(engineer.id, () => service.proposal(row.id, row.version, proposal))); checks++;
    await assert.rejects(act(engineer.id, () => service.action(row.id, { version: row.version, action: 'start' }))); checks++;
    const execution = await prisma.workOrder.create({ data: { tenantId, assetCode: asset.code, title: 'Instalar guía', kind: 'SERVICE_ORDER', status: 'OPEN' } });
    row = await act(engineer.id, () => service.linkOrder(row.id, row.version, execution.id));
    await apply(engineer.id, 'start');
    await apply(admin.id, 'hold', { note: 'Esperando parada' });
    await apply(admin.id, 'resume');
    assert.equal(row.status, 'EXECUTION'); checks++;
    await apply(engineer.id, 'validate');
    const closure = { action: 'close', criteriaMet: true, validationResult: 'Dos horas sin atascos', documentUpdates: 'Plano y manual rev. B' };
    await assert.rejects(act(reviewer.id, () => service.action(row.id, { version: row.version, ...closure }))); checks++;
    await prisma.workOrder.update({ where: { id: execution.id }, data: { status: 'COMPLETED' } });
    await apply(reviewer.id, 'close', closure);
    assert.equal(row.status, 'CLOSED');
    assert.equal(row.events.at(-1).details.criteriaMet, true);
    await assert.rejects(act(admin.id, () => service.comment(row.id, row.version, 'Cambio posterior'))); checks++;
    console.log('Engineering integration passed: ' + checks + ' checks, full lifecycle and immutable revisions.');
  } finally {
    const where = { tenantId: { in: [tenantId, otherTenantId] } };
    await prisma.attachment.deleteMany({ where });
    await db.engineeringRequestOrder.deleteMany({ where });
    await db.engineeringRequestEvent.deleteMany({ where });
    await db.engineeringRequestRevision.deleteMany({ where });
    await db.engineeringRequest.deleteMany({ where });
    await prisma.workOrder.deleteMany({ where });
    await prisma.asset.deleteMany({ where });
    await prisma.user.deleteMany({ where });
    await prisma.tenant.deleteMany({ where: { id: { in: [tenantId, otherTenantId] } } });
    await prisma.$disconnect();
    await unlink(filePath).catch(() => {});
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
